import {chromium} from 'playwright-core';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const directions=['clear-desk','night-shift','paper-ledger'];const screens=['portfolio','bench','assistant','settings'];
mkdirSync('evidence/mockups',{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const results=[];
try{for(const dir of directions){for(const width of [390,1440]){for(const screen of screens){const page=await browser.newPage({viewport:{width,height:960},deviceScaleFactor:1});const errors=[];const requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto('file://'+resolve(`mockups/${dir}/${screen}.html`));await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${dir}/${screen}/${width} page overflow`);assert.deepEqual(errors,[]);assert.equal(requests.some(u=>/^https?:/.test(u)),false);assert.equal(await page.getByText('SAMPLE DATA · STATIC MOCKUP · NOT CONNECTED',{exact:true}).count(),1);assert.equal(await page.getByText('＋ Give feedback',{exact:true}).count(),1);if(screen==='assistant'){assert.equal(await page.locator('select').first().locator('option').count(),7);assert.equal(await page.locator('.job').count(),3);}const file=`${dir}-${screen}-${width}.png`;await page.screenshot({path:'evidence/mockups/'+file,fullPage:true});const dims=await page.evaluate(()=>({width:innerWidth,height:document.documentElement.scrollHeight}));const record={file,...dims,errors,externalRequests:requests.filter(u=>/^https?:/.test(u)),sampleLabel:true,feedbackPreview:true,capturedAt:new Date().toISOString()};results.push(record);console.log('PASS mockup',JSON.stringify(record));await page.close();}
const mobile=width===390;const thumb=mobile?300:700;const columns=mobile?4:2;const html=`<html><body style="margin:0;background:#d7dce0;padding:20px;font:16px system-ui"><h1>${dir} / ${width}px</h1><div style="display:grid;grid-template-columns:repeat(${columns},${thumb}px);gap:16px">${screens.map(s=>`<div><b>${s}</b><img style="display:block;width:${thumb}px" src="file://${resolve(`evidence/mockups/${dir}-${s}-${width}.png`)}"></div>`).join('')}</div></body></html>`;const sheet=await browser.newPage({viewport:{width:columns*(thumb+16)+24,height:960}});const sheetPath=resolve(`evidence/mockups/${dir}-${width}-contact.html`);writeFileSync(sheetPath,html);await sheet.goto("file://"+sheetPath);await sheet.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await sheet.screenshot({path:`evidence/mockups/${dir}-${width}-contact.png`,fullPage:true});await sheet.close();}}writeFileSync('evidence/render-results.json',JSON.stringify(results,null,2));}finally{await browser.close()}
