import assert from 'node:assert/strict';import {writeFileSync,mkdirSync} from 'node:fs';
import {publicExchange} from '../dist/market.js';import {privateReader,checkPermissions} from '../dist/sources.js';import {totp} from '../dist/security.js';
const base=process.env.BASE??'http://127.0.0.1:8080',output=process.env.OUTPUT??'/tmp/v074-runtime';mkdirSync(output,{recursive:true});let cookie='';const results=[];
async function api(path,body,method='POST',auth=cookie,headers={}){const r=await fetch(base+'/api/'+path,{method:body===undefined?'GET':method,headers:{'content-type':'application/json',cookie:auth,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
function check(name,ok,details={}){results.push({check:name,result:ok?'PASS':'FAIL',...details,capturedAt:new Date().toISOString()});console.log(JSON.stringify(results.at(-1)));assert.ok(ok,name);}
try{
const gets=['sources','settings','tickers','staking/view','trends/view','staking','backtests','backtests/1','backtests/1/report','backtests/latest','portfolio/history','portfolio/history.csv','notifications','portfolio','portfolio.csv','providers','ai/usage','holdouts','jobs','news'];
const posts=['sources/notice','sources/kraken','sources/kraken/test','auth/logout','auth/totp/start','auth/totp/confirm','settings','feedback','usage','staking/view','trends/view','trends','trends/snapshot','backtest/rules','backtest','backtests/compare','backtests/1/replay','holdouts','holdouts/1/unseal','portfolio','providers','providers/openai/controls','providers/openai/approve','chat','jobs','bench-preset','notifications/telegram','notifications/telegram/test','update/check'];
for(const [method,paths] of [['GET',gets],['POST',posts],['DELETE',['sources/kraken/key','notifications/telegram','portfolio/1']]])for(const path of paths){const r=await api(path,method==='GET'?undefined:{},method,'');check('unauth '+method+' '+path,r.status===401,{status:r.status});}
const state=await api('auth/state');cookie=(await api(state.body.setup?'auth/setup':'auth/login',{password:'Synthetic browser fixture password 074'})).cookie;check('authenticated workspace available',!!cookie);
check('setup replay refused',(await api('auth/setup',{password:'Synthetic browser fixture password 074'})).status===409);
check('foreign origin refused',(await api('settings',{},'POST',cookie,{origin:'https://foreign.example'})).status===403);
check('non-JSON refused',(await api('settings',{},'POST',cookie,{'content-type':'text/plain'})).status===415);
check('telemetry off',(await api('usage',{event:'screen:bench'})).body.counted===false);await api('settings',{telemetry:true});check('allowlisted telemetry counted',(await api('usage',{event:'screen:bench'})).body.counted===true);check('arbitrary telemetry refused',(await api('usage',{event:'CTREVIEW-SMTPPASS-synthetic-notlive'})).status===400);await api('settings',{telemetry:false});
const metadata=JSON.stringify((await api('providers')).body)+JSON.stringify((await api('notifications')).body)+JSON.stringify((await api('sources')).body);check('metadata hides canary credentials',!metadata.includes('synthetic-notlive'));
const saved=await api('sources/kraken',{enabled:true,accepted:true});check('keyless source enabled',saved.status===200);
await api('portfolio',{symbol:'BTC/USDT',quantity:1.5,cost:60000});
for(const path of ['portfolio.csv','portfolio/history.csv?days=7']){const r=await fetch(base+'/api/'+path,{headers:{cookie}});assert.equal(r.status,200);writeFileSync(output+'/'+path.split('?')[0].replaceAll('/','-'),await r.text());check('export '+path,true);}
const end=Math.floor(Date.now()/86400000)*86400000;const bench=await api('backtest',{exchange:'kraken',symbol:'BTC/USDT',timeframe:'1d',start:end-120*86400000,end,capital:10000,strategy:'sma',fast:5,slow:20,feeMode:'exchange',slippageModel:'flat',slippageBps:5});check('real Kraken 120-day saved backtest',bench.status===200,{status:bench.status,bars:bench.body.equity?.length,source:bench.body.coverage?.source});
const report=await fetch(base+'/api/backtests/'+bench.body.runId+'/report',{headers:{cookie}});assert.equal(report.status,200);writeFileSync(output+'/report.html',await report.text());check('saved HTML report exported',true);
const ex=publicExchange('kraken');await ex.loadMarkets();ex.apiKey='synthetic-notlive';ex.secret=Buffer.from('synthetic-notlive').toString('base64');
for(const [name,args] of [['createOrder',['BTC/USD','market','buy',1]],['cancelOrder',['fixture','BTC/USD']],['fetchBalance',[]],['withdraw',['BTC',1,'fixture']],['fetchMyTrades',['BTC/USD']]]){let error;try{await ex[name](...args);}catch(e){error=e.message;}check('public boundary '+name,error==='Public data boundary violation',{error});}
const privateEx=privateReader('kraken-earn',{key:'synthetic-notlive',secret:Buffer.from('synthetic-notlive').toString('base64')});let error;try{await privateEx.fetch('https://api.kraken.com/0/private/AddOrder','POST');}catch(e){error=e.message;}check('read-only signed POST boundary',error==='Read-only endpoint boundary',{error});
const safe={enableReading:true,enableWithdrawals:false,enableSpotAndMarginTrading:false,enableMargin:false,enableFutures:false,enableVanillaOptions:false,enableInternalTransfer:false,permitsUniversalTransfer:false};
for(const [name,id,fixture,allowed] of [['binance read only','binance-earn',safe,true],['binance trade','binance-earn',{...safe,enableSpotAndMarginTrading:true},false],['binance withdrawal','binance-earn',{...safe,enableWithdrawals:true},false],['binance unknown flag','binance-earn',{...safe,enableUnknown:true},false],['binance reading off','binance-earn',{...safe,enableReading:false},false],['okx read only','okx-earn',{code:'0',data:[{perm:'read_only'}]},true],['okx trade','okx-earn',{code:'0',data:[{perm:'read_only,trade'}]},false],['okx trade only','okx-earn',{code:'0',data:[{perm:'trade'}]},false],['kraken query','kraken-earn',{error:[],result:{permissions:['query-funds']}},true],['kraken withdraw','kraken-earn',{error:[],result:{permissions:['withdraw-funds']}},false],['kraken order','kraken-earn',{error:[],result:{permissions:['create-order']}},false]]){let accepted=true;try{checkPermissions(id,fixture)}catch{accepted=false}check('permissions '+name,accepted===allowed,{accepted});}
const before=cookie,pending=await api('auth/totp/start',{}),confirmed=await api('auth/totp/confirm',{code:totp(pending.body.secret)});cookie=confirmed.cookie;check('TOTP confirm rotates current session',confirmed.status===200&&!!cookie);check('old session invalidated on TOTP enable',(await api('settings',undefined,'GET',before)).status===401);const login=await api('auth/login',{password:'Synthetic browser fixture password 074',code:totp(pending.body.secret)});check('standard TOTP login works',login.status===200);cookie=login.cookie;
const old=cookie;await api('auth/logout',{});check('logout replay refused',(await api('settings',undefined,'GET',old)).status===401);
for(let n=1;n<=6;n++)check('bad login attempt '+n,(await api('auth/login',{password:'wrong'})).status===(n<=5?401:429));check('correct login remains rate limited',(await api('auth/login',{password:'Synthetic browser fixture password 074',code:totp(pending.body.secret)})).status===429);
}finally{writeFileSync(output+'/checks.json',JSON.stringify(results,null,2));}
