import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const output=process.env.OUTPUT??'/home/cowork/v074-security/browser',base=process.env.BASE??'http://127.0.0.1:8095',sandbox=process.env.SANDBOX==='1';mkdirSync(output,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const results=[];
async function api(page,path,body){const r=await page.request[body===undefined?'get':'post'](base+'/api/'+path,body===undefined?{}:{data:body});return {status:r.status(),body:await r.json()};}
try{for(const theme of ['night','clear'])for(const width of [390,1440]){
 const context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 const state=await api(page,'auth/state');const login=await api(page,state.body.setup?'auth/setup':'auth/login',{password:'Synthetic browser fixture password 074'});assert.equal(login.status,200);
 await api(page,'settings',{onboarded:true});await page.evaluate(theme=>localStorage.setItem('theme',theme),theme);await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('.notification-settings').waitFor();
 const check=(name,details)=>results.push({theme,width,sandbox,check:name,...details,capturedAt:new Date().toISOString()});
 const capture=async(name,locator=page)=>{const file=`${sandbox?'sandbox':'normal'}-${theme}-${width}-${name}.png`;await locator.screenshot({path:output+'/'+file});check(name,{artifact:file});};
 const smtp=page.locator('.channel-form').filter({has:page.getByRole('heading',{name:'Email · own SMTP'})});
 const toggle=smtp.getByRole('checkbox',{name:'Allow local/private SMTP server'});assert.equal(await toggle.isDisabled(),sandbox);assert.equal(await toggle.isChecked(),false);assert.match(await smtp.innerText(),/Warning:.*internal network/);await capture('smtp-toggle',smtp);
 if(!sandbox){
 await api(page,'notifications/email',{enabled:false,events:[],credentials:{host:'127.0.0.1',port:587,secure:false,user:'fixture',password:'CTREVIEW-BROWSER-SMTP-synthetic-notlive',from:'a@example.org',to:'b@example.org'}});
 await page.getByRole('button',{name:'Send feedback',exact:true}).click();await page.getByRole('textbox',{name:'Comment'}).fill('Diagnostic CTREVIEW-BROWSER-SMTP-synthetic-notlive');await page.getByRole('button',{name:'Send comment',exact:true}).click();await page.getByRole('dialog',{name:'Feedback',exact:true}).getByRole('alert').filter({hasText:'Nothing was sent'}).waitFor();await capture('feedback-blocked');await page.getByRole('button',{name:'Close',exact:true}).click();
 const saved=await api(page,'providers',{provider:'ollama',model:'fixture',key:'CTREVIEW-BROWSER-AI-synthetic-notlive',baseUrl:'http://127.0.0.1:11434/v1',allowLocalOllama:true});assert.equal(saved.status,200);await api(page,'providers/ollama/approve',{confirm:true,model:'fixture',baseUrl:'http://127.0.0.1:11434/v1'});await api(page,'providers/ollama/controls',{dailyCap:1000000,rpm:100,noPortfolio:true});
 await page.getByRole('button',{name:'Assistant',exact:true}).click();await page.getByLabel('Chat provider',{exact:true}).selectOption('ollama');
 await page.getByRole('textbox',{name:'Message',exact:true}).fill('forbidden tool');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.locator('main > .error').filter({hasText:'Tool forbidden. Only the supplied read-only tools are permitted.'}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await capture('tool-refusal');
 await page.getByRole('textbox',{name:'Message',exact:true}).fill('disabled source');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.locator('main > .error').filter({hasText:'Source disabled. Choose and accept it in Data sources.'}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await capture('permission-refusal');
 }else{
 const refused=await api(page,'sources/defillama-pro',{enabled:false,accepted:true,credentials:{key:'synthetic-notlive'}});assert.equal(refused.status,400);assert.equal(refused.body.error,'Install locally to use your own keys');check('sandbox intended source refusal',{status:refused.status,error:refused.body.error});
 // Exercise the real UI error path with a deliberately tampered disabled form control.
 await page.getByLabel('Provider',{exact:true}).selectOption('ollama');await page.locator('input[name=model]').fill('fixture');await page.locator('input[name=baseUrl]').fill('http://127.0.0.1:11434/v1');const local=page.locator('input[name=allowLocalOllama]');assert.ok(await local.isDisabled());await local.evaluate(el=>{el.disabled=false;el.checked=true});await page.getByRole('button',{name:'Save provider',exact:true}).click();await page.locator('main > .error').filter({hasText:'Local Ollama access is unavailable for this provider or in sandbox mode.'}).waitFor();await local.evaluate(el=>{el.disabled=true;el.checked=false});await page.evaluate(()=>window.scrollTo(0,0));await capture('sandbox-refusal');
 }
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);assert.ok(overflow<=1,'horizontal overflow '+overflow);assert.deepEqual(errors,[]);check('layout and JS checks',{horizontalOverflow:overflow,pageErrors:errors.length});await context.close();
}}finally{await browser.close();writeFileSync(output+'/checks.json',JSON.stringify(results,null,2));}
console.log(JSON.stringify({checks:results.length,sandbox,capturedAt:new Date().toISOString(),output}));
