// Disposable workspace only. Synthetic canary credentials are never real provider keys.
import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const base=process.env.TEST_URL??'http://127.0.0.1:8084',out=process.env.TEST_OUTPUT??'evidence-byo',sandbox=process.env.TEST_SANDBOX==='1';mkdirSync(out+'/screens',{recursive:true});const errors=[],captures=[],checks=[];const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));assert.equal((await context.request.get(base+'/api/sources')).status(),401);const authState=await(await context.request.get(base+'/api/auth/state')).json();const auth=await context.request.post(base+'/api/auth/'+(authState.setup?'setup':'login'),{data:{password:'BYO disposable workspace password 2026!'}});assert.equal(auth.status(),200);
 const request=async(path,data)=>{const r=await context.request.post(base+'/api/'+path,{data});assert.equal(r.status(),200,path);return r.json();};let sources=await(await context.request.get(base+'/api/sources')).json();assert.equal(sources.sources.length,12);assert.ok(sources.sources.every(s=>!s.enabled&&!s.accepted));assert.equal(sources.sandbox,sandbox);assert.deepEqual((await(await context.request.get(base+'/api/tickers')).json()).tickers,[]);assert.equal((await(await context.request.get(base+'/api/staking')).json()).total,0);assert.equal((await context.request.post(base+'/api/sources/lido',{data:{accepted:false,enabled:true}})).status(),400);assert.equal((await context.request.post(base+'/api/sources/lido/test',{data:{}})).status(),400);assert.equal((await context.request.post(base+'/api/backtest',{data:{exchange:'kraken',symbol:'BTC/USDT',timeframe:'1d',start:'2026-01-01',end:'2026-02-01'}})).status(),400);checks.push('API auth; twelve default-off connectors; empty ticker/staking responses; terms required; disabled test and history refused');
 await page.goto(base);await page.getByRole('dialog',{name:'Onboarding'}).waitFor();await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('dialog',{name:'Onboarding'}).getByRole('heading',{name:'Choose your data sources',exact:true}).waitFor();
 const capture=async(name)=>{const originalTheme=await page.evaluate(()=>document.documentElement.dataset.theme);for(const width of [390,1440]){await page.setViewportSize({width,height:960});for(const theme of ['night','clear']){if(name==='onboarding')await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);else if(await page.evaluate(()=>document.documentElement.dataset.theme)!==theme)await page.getByRole('button',{name:'Switch theme'}).click();await page.waitForFunction(t=>document.documentElement.dataset.theme===t,theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' page overflow');const path=out+'/screens/'+theme+'-'+name+'-'+width+'.png';await page.screenshot({path,fullPage:true});captures.push({path,capturedAt:new Date().toISOString(),width,theme});console.log('PASS render',name,theme,width);}}if(name==='onboarding')await page.evaluate(t=>document.documentElement.dataset.theme=t,originalTheme);};
 await page.locator('.source-onboarding .source-card').first().waitFor();await capture('onboarding');await page.getByRole('button',{name:'Continue / skip sources'}).click();await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Open workspace',exact:true}).click();await page.getByRole('heading',{name:'Choose your data sources',exact:true}).waitFor();await capture('empty');await page.getByRole('button',{name:'Open Data sources',exact:true}).click();await page.locator('[data-source="lido"]').waitFor();await capture(sandbox?'sandbox-sources':'sources');
 if(sandbox){for(const id of ['kraken-earn','binance-earn','okx-earn','defillama-pro']){const card=page.locator(`[data-source="${id}"]`);assert.equal(await card.locator('input[name="key"]').isDisabled(),true);assert.equal((await context.request.post(base+'/api/sources/'+id,{data:{enabled:true,accepted:true,credentials:{key:'synthetic-notlive',secret:'synthetic-notlive-secret',passphrase:'synthetic-notlive-passphrase'}}})).status(),400);}checks.push('sandbox UI key fields disabled and backend rejects credentials for all keyed sources');}
 else{
 // Canary uses the same exact bytes as prepare-scan.mjs, assembled without printing.
 const key=['sk','step3','synthetic','notlive','0123456789'].join('-');await request('sources/defillama-pro',{enabled:false,accepted:true,credentials:{key}});sources=await(await context.request.get(base+'/api/sources')).json();assert.ok(!JSON.stringify(sources).includes(key));const feedback=await context.request.post(base+'/api/feedback',{data:{comment:'Test '+key,screen:'sources',version:'0.5.0'}});assert.equal(feedback.status(),400);writeFileSync(out+'/key-metadata.json',JSON.stringify({capturedAt:new Date().toISOString(),sources,feedbackStatus:feedback.status()},null,2));assert.equal((await context.request.delete(base+'/api/sources/defillama-pro/key',{data:{}})).status(),200);checks.push('synthetic exact-byte key hidden from API metadata, rejected in feedback, deletable');
 // Enable free feed through actual UI, acceptance and switch are independent.
 const card=page.locator('[data-source="defillama"]');assert.equal(await card.getByLabel('Enable DefiLlama free',{exact:true}).isDisabled(),true);await card.getByText('I have read and accept this provider’s terms; I use this source under my own account',{exact:true}).click();await card.getByLabel('Enable DefiLlama free',{exact:true}).check();await card.getByRole('button',{name:'Save source',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-source="defillama"] .badge')?.textContent==='Enabled');await card.getByRole('button',{name:'Test connection',exact:true}).click();await card.getByText(/Last status: Fetch succeeded/).waitFor({timeout:30000});await page.getByRole('button',{name:'Staking',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length>0,{},{timeout:45000});const real=await(await context.request.get(base+'/api/staking')).json();assert.ok(real.total>0);assert.ok(real.options.every(o=>o.source==='DefiLlama free API'&&o.custody==='unknown'&&o.sourceTimestamp===null));assert.ok(real.options.some(o=>typeof o.apy==='number'));assert.ok(Date.now()-Date.parse(real.options[0].fetchedAt)<900000);writeFileSync(out+'/real-staking-data.json',JSON.stringify({capturedAt:new Date().toISOString(),...real},null,2));
 // Neutral user filter reduces the screenshot, but the data remains real.
 await page.getByLabel('Asset filter',{exact:true}).fill(real.options.map(o=>o.asset).sort((a,b)=>b.length-a.length)[0]);await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length>0&&document.querySelectorAll('.staking-table tbody tr').length<30,{},{timeout:20000});await capture('staking-defillama');const cached=await(await context.request.get(base+'/api/staking')).json();assert.equal(cached.options[0].fetchedAt,real.options[0].fetchedAt);await request('sources/defillama',{enabled:false,accepted:true});assert.equal((await(await context.request.get(base+'/api/staking')).json()).total,0);checks.push('real free DefiLlama data; UI terms + enable + connection test; unknown custody/timestamps; neutral filter; timestamp-preserving cache; disable hides cached feed');
 }
 for(const path of ['orders','staking/deposit','staking/stake','staking/withdraw'])assert.equal((await context.request.post(base+'/api/'+path,{data:{}})).status(),404);assert.deepEqual(errors,[]);writeFileSync(out+'/browser-result.json',JSON.stringify({capturedAt:new Date().toISOString(),ok:true,sandbox,errors,captures,checks},null,2));console.log('PASS BYO integration',JSON.stringify({sandbox,captures:captures.length,checks}));await context.close();
}finally{await browser.close()}
