import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const base=process.env.TEST_URL??'http://127.0.0.1:8084',output='evidence-staking';mkdirSync(output+'/screens',{recursive:true});const errors=[],captures=[];
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const anonymous=await context.request.get(base+'/api/staking');assert.equal(anonymous.status(),401);const state=await(await context.request.get(base+'/api/auth/state')).json();const auth=await context.request.post(base+'/api/auth/'+(state.setup?'setup':'login'),{data:{password:'Staking disposable test workspace 2026!'}});assert.equal(auth.status(),200);assert.equal((await context.request.post(base+'/api/settings',{data:{onboarded:true,survey:true}})).status(),200);
 const response=await context.request.get(base+'/api/staking');assert.equal(response.status(),200);const data=await response.json();assert.equal(data.total,1);assert.equal(data.options.length,1);assert.equal(data.sort.column,'asset');const option=data.options[0];assert.equal(option.source,'Lido public API');assert.equal(option.apy,null);assert.ok(Number.isFinite(option.apr));assert.ok(Date.now()-Date.parse(option.fetchedAt)<900000,'REAL source retrieval within the cache interval required');assert.ok(option.sourceTimestamp);assert.equal(option.custody,'user on-chain');writeFileSync(output+'/real-staking-data.json',JSON.stringify({capturedAt:new Date().toISOString(),...data},null,2));
 for(const [query,count] of [['asset=ETH',1],['asset=BTC',0],['type=exchange+earn',0],['type=liquid+staking',1],['custody=user+on-chain',1],['custody=exchange+holds+coins',0],['minTvlUsd=0',0],['maxLockDays=0',0],['hidePromo=true',0]]){const r=await context.request.get(base+'/api/staking?'+query);assert.equal(r.status(),200);assert.equal((await r.json()).options.length,count,query);}
 for(const query of ['sort=best','hidePromo=maybe','maxLockDays=-1','minTvlUsd=NaN','deposit=true','maxLockDays='])assert.equal((await context.request.get(base+'/api/staking?'+query)).status(),400,query);
 for(const path of ['staking/deposit','staking/stake','staking/withdraw','orders'])assert.equal((await context.request.post(base+'/api/'+path,{data:{}})).status(),404,path);
 await page.goto(base);await page.getByRole('button',{name:'Staking',exact:true}).click();await page.getByRole('cell',{name:/ETH \/ stETH/}).waitFor();assert.equal(await page.getByLabel('Sort column',{exact:true}).inputValue(),'asset');
 for(const width of [390,768,1024,1440]){await page.setViewportSize({width,height:960});for(const theme of ['night','clear']){if(await page.evaluate(()=>document.documentElement.dataset.theme)!==theme)await page.getByRole('button',{name:'Switch theme'}).click();await page.waitForFunction(t=>document.documentElement.dataset.theme===t,theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'page overflow '+theme+' '+width);assert.equal(await page.locator('.staking-table').evaluate(e=>e.scrollWidth>e.parentElement.clientWidth),false,'table overflow '+theme+' '+width);const body=await page.locator('section[aria-label="Staking information"]').innerText();assert.match(body,/Not financial advice/);assert.match(body,/one verified Lido/);assert.match(body,/APR is not APY/);assert.match(body,/unknown/);assert.match(body,/cached snapshot/);for(const a of await page.locator('section[aria-label="Staking information"] a').evaluateAll(items=>items.map(a=>a.href))){assert.equal(new URL(a).search,'');assert.ok(!/affiliate|referral/i.test(a));}const path=output+'/screens/'+theme+'-staking-'+width+'.png';await page.screenshot({path,fullPage:true});captures.push({path,capturedAt:new Date().toISOString(),width,theme,sourceFetchedAt:option.fetchedAt});console.log('PASS REAL render',JSON.stringify(captures.at(-1)));}}
 await page.setViewportSize({width:390,height:960});const ui=async(label,value,count)=>{const selected=page.getByLabel(label,{exact:true});if(await selected.inputValue()===value){assert.equal(await page.locator('.staking-table tbody tr').count(),count);return;}const pending=page.waitForResponse(r=>r.url().includes('/api/staking?')&&r.status()===200);if((await selected.evaluate(e=>e.tagName))==='SELECT')await selected.selectOption(value);else await selected.fill(value);await pending;await page.waitForFunction(n=>document.querySelectorAll('.staking-table tbody tr').length===n,count);};
 await ui('Asset filter','BTC',0);await ui('Asset filter','ETH',1);await ui('Min TVL (USD)','0',0);await ui('Min TVL (USD)','',1);await ui('Max lock-up (days)','0',0);await ui('Max lock-up (days)','',1);await ui('Type filter','exchange earn',0);await ui('Type filter','liquid staking',1);await ui('Custody filter','exchange holds coins',0);await ui('Custody filter','user on-chain',1);
 for(const [key,label] of [['asset','Asset'],['venue','Venue'],['type','Type'],['apy','APY'],['apr','APR'],['rateType','Rate type'],['lockDays','Lock'],['custody','Custody'],['risks','Listed risks'],['minimum','Minimum'],['tvlUsd','TVL'],['source','Source'],['fetchedAt','Fetched'],['sourceTimestamp','Observed']]){await ui('Sort column',key,1);}
 await ui('Sort direction','desc',1);await page.getByRole('button',{name:'Reset view',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length===1);const promo=page.getByLabel('Hide promo or unknown promo status',{exact:true});await promo.check();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length===0);await promo.uncheck();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length===1);
 assert.deepEqual(errors,[]);const cached=await(await context.request.get(base+'/api/staking')).json();assert.equal(cached.options[0].fetchedAt,option.fetchedAt);writeFileSync(output+'/browser-result.json',JSON.stringify({capturedAt:new Date().toISOString(),ok:true,errors,captures,checks:['real public data','both themes four widths','zero page/table overflow','auth required','filters and 14 sort columns','unknown fields fail closed','invalid input 400','deposit/stake/withdraw/order routes 404','cached source time preserved','outbound links without referrals']},null,2));console.log('PASS source-limited staking browser integration; eight REAL renders; zero errors');await context.close();
}finally{await browser.close();}
