import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const base=process.env.TEST_URL??'http://127.0.0.1:8084',out=process.env.TEST_OUTPUT??'trends-evidence/browser';mkdirSync(out+'/screens',{recursive:true});const captures=[],checks=[],errors=[],browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));let auth=await(await context.request.get(base+'/api/auth/state')).json();assert.equal((await context.request.post(base+'/api/auth/'+(auth.setup?'setup':'login'),{data:{password:'Trends disposable workspace 2026!'}})).status(),200);const request=async(path,data)=>{const r=await context.request.post(base+'/api/'+path,{data});assert.equal(r.status(),200,path);return r.json()};
 if(process.env.INIT_SOURCES==='1'){const initial=await(await context.request.get(base+'/api/sources')).json();assert.ok(initial.sources.every(s=>!s.enabled));const empty=await request('trends',{metric:'leaders'});assert.deepEqual(empty.sources,[]);for(const id of ['kraken','okx','defillama'])await request('sources/'+id,{accepted:true,enabled:true});await request('settings',{onboarded:true,survey:true});await request('staking/view',{presets:['tvl'],asset:'ETH',minTvlUsd:10000000,sort:'tvlUsd',direction:'desc'});}
 await request('staking/view',{presets:['tvl'],asset:'ETH',minTvlUsd:10000000,sort:'tvlUsd',direction:'desc'});
 await page.goto(base);await page.getByRole('button',{name:'Trends',exact:true}).click();await page.getByRole('heading',{name:'Combined volume · USD-equivalent',exact:true}).waitFor({timeout:120000});
 const capture=async(name)=>{for(const width of [390,1440]){await page.setViewportSize({width,height:960});for(const theme of ['night','clear']){if(await page.evaluate(()=>document.documentElement.dataset.theme)!==theme)await page.getByRole('button',{name:'Switch theme'}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' page overflow');await page.waitForTimeout(150);const text=await page.locator('body').innerText();assert.equal(/\b(?:bullish|bearish|buy|sell|recommend(?:s|ed|ing|ation|ations)?)\b/i.test(text.replace('Every trade has a buyer and a seller. This shows which side was more eager (crossed the spread), not that more people bought than sold.','')),false,name+' visible neutrality');const path=out+'/screens/'+theme+'-'+name+'-'+width+'.png';await page.screenshot({path,fullPage:true});await page.screenshot({path:out+'/screens/'+theme+'-'+name+'-'+width+'-viewport.png'});const detail=page.locator(name==='staking-presets'?'.staking-results':name==='bench-link'?'.split':'.trend-results article').last();await detail.screenshot({path:out+'/screens/'+theme+'-'+name+'-'+width+'-detail.png'});captures.push({path,capturedAt:new Date().toISOString(),width,theme});console.log('PASS render',name,theme,width);}}};
 const real=await request('trends',{metric:'leaders'});assert.deepEqual(real.sources.map(s=>s.exchange),['kraken','okx']);assert.ok(real.sources.every(s=>s.rows.length>0&&s.fetchedAt));writeFileSync(out+'/real-leaders.json',JSON.stringify({capturedAt:new Date().toISOString(),...real},null,2));await capture('leaders');
 await page.getByRole('button',{name:'Volume surges',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.trend-results')?.textContent.includes('/30 complete daily candles'),{},{timeout:120000});await capture('surges');
 await page.getByRole('button',{name:'Aggressor flow',exact:true}).click();await page.getByRole('heading',{name:'Observed sample only',exact:true}).waitFor({timeout:120000});await capture('flow');
 await page.getByRole('button',{name:'New listings',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.trend-results')?.textContent.includes('active spot markets'),{},{timeout:120000});await capture('listings');
 await page.getByRole('button',{name:'Futures positioning',exact:true}).click();await page.locator('select[name="exchange"]').selectOption('okx');await page.getByRole('button',{name:'Read selected market',exact:true}).click();await page.getByRole('heading',{name:'BTC/USDT:USDT',exact:true}).waitFor({timeout:120000});await capture('futures');
 await page.getByRole('button',{name:'Test in bench · past behaviour',exact:true}).click();await page.getByRole('heading',{name:'Define a test',exact:true}).waitFor();assert.equal(await page.locator('select[name="exchange"]').inputValue(),'okx');assert.equal(await page.locator('input[name="symbol"]').inputValue(),'BTC/USDT');assert.ok((await page.locator('[role="note"]').innerText()).includes('past behaviour'));await capture('bench-link');checks.push('real leaders/surges/flow/listings/futures from two enabled public venues; both themes/widths; actual bench preselection');
 await page.getByRole('button',{name:'Staking',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length>0,{},{timeout:120000});assert.equal(await page.getByLabel('TVL at least $10M',{exact:true}).isChecked(),true);await page.getByLabel('Staking and liquid staking only',{exact:true}).check();await page.waitForTimeout(800);const view=await(await context.request.get(base+'/api/staking/view')).json();assert.ok(view.presets.includes('staking')&&view.presets.includes('tvl'));await page.reload();await page.getByRole('button',{name:'Staking',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.preset-grid label input')?.checked===true);assert.equal(await page.getByLabel('Staking and liquid staking only',{exact:true}).isChecked(),true);await page.getByLabel('Staking and liquid staking only',{exact:true}).uncheck();await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length>0,{},{timeout:45000});const pools=await(await context.request.get(base+'/api/staking?asset=ETH&minTvlUsd=10000000')).json();const narrow=[...pools.options].sort((a,b)=>b.asset.length-a.asset.length).find(o=>pools.options.filter(p=>p.asset.includes(o.asset)).length<=4)?.asset??pools.options[0].asset;await page.getByLabel('Asset filter',{exact:true}).fill(narrow);await page.waitForFunction(()=>document.querySelectorAll('.staking-table tbody tr').length>0&&document.querySelectorAll('.staking-table tbody tr').length<10);await capture('staking-presets');checks.push('preset combination saved to SQLite and survives reload; real source unknown classifications excluded honestly');
 // Every metric must hide its cache when the source is switched off.
 for(const id of ['kraken','okx'])await request('sources/'+id,{accepted:true,enabled:false});for(const metric of ['leaders','surges','flow','listings','futures']){const disabled=await request('trends',{metric,exchange:'okx',symbol:'BTC/USDT'});assert.deepEqual(disabled.sources,[]);assert.deepEqual(disabled.combined,[]);}checks.push('disable hides all five cached metrics');for(const id of ['kraken','okx'])await request('sources/'+id,{accepted:true,enabled:true});assert.deepEqual(errors,[]);writeFileSync(out+'/browser-result.json',JSON.stringify({capturedAt:new Date().toISOString(),ok:true,errors,captures,checks},null,2));console.log('PASS browser',JSON.stringify({captures:captures.length,checks}));await context.close();
}finally{await browser.close()}
