import type {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
export const privacyNotice='This provider may log or train on your questions and the portfolio data the assistant sends. Use a paid or local model for private data.';
export class ControlError extends Error { constructor(message:string,readonly code:string){super(message);} }
export const zenChatModels=['qwen3.8-max','deepseek-v4.1-flash','deepseek-v4-pro','deepseek-v4-flash','deepseek-v4-flash-vision-exp','minimax-m3','minimax-m2.7','glm-5.3-flash','glm-5.3','glm-5.2','glm-5.1','kimi-k2.6','kimi-k2.7-code','kimi-k3','mistral-large-4','big-pickle','space-bunny-free','longcat-2.5-preview-free','exo-free','fledge-alpha-free','mimo-v2.6-flash-free','mimo-v2.5-free','ling-3.1-flash-free','ling-3.0-flash-fin-free','nemotron-3-ultra-free','nemotron-3.5-lightning-free'];
export function privacyRisk(provider:string,model:string,baseUrl:string){return !!baseUrl||/(?:free|stealth|unknown|big-pickle)/i.test(model)||(provider==='zen'&&!zenChatModels.includes(model));}
const identity=(model:string,baseUrl:string)=>createHash('sha256').update(JSON.stringify([model,baseUrl])).digest('hex');
export class AIControls {
 constructor(private db:DatabaseSync,private clock=Date.now,private onCap:()=>void=()=>{}){
 db.exec(`CREATE TABLE IF NOT EXISTS ai_controls(provider TEXT PRIMARY KEY,daily_cap INTEGER,rpm INTEGER,no_portfolio INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS ai_approvals(provider TEXT,identity TEXT,PRIMARY KEY(provider,identity)); CREATE TABLE IF NOT EXISTS ai_debits(id INTEGER PRIMARY KEY,provider TEXT,day TEXT,at INTEGER,tokens INTEGER NOT NULL,estimate INTEGER NOT NULL)`);
 }
 settings(provider:string){return (this.db.prepare('SELECT daily_cap AS dailyCap,rpm,no_portfolio AS noPortfolio FROM ai_controls WHERE provider=?').get(provider) as any)??{dailyCap:50000,rpm:10,noPortfolio:0};}
 update(provider:string,b:any){if(!b||Object.keys(b).some(k=>!['dailyCap','rpm','noPortfolio'].includes(k))||!(b.dailyCap===null||Number.isSafeInteger(b.dailyCap)&&b.dailyCap>=0&&b.dailyCap<=1e9)||!(b.rpm===null||Number.isSafeInteger(b.rpm)&&b.rpm>=1&&b.rpm<=1000)||typeof b.noPortfolio!=='boolean')throw Error('Invalid AI controls');this.db.prepare('INSERT OR REPLACE INTO ai_controls VALUES(?,?,?,?)').run(provider,b.dailyCap,b.rpm,b.noPortfolio?1:0);return this.meter(provider);}
 approved(provider:string,model:string,baseUrl:string){return !privacyRisk(provider,model,baseUrl)||!!this.db.prepare('SELECT 1 FROM ai_approvals WHERE provider=? AND identity=?').get(provider,identity(model,baseUrl));}
 approve(provider:string,model:string,baseUrl:string){this.db.prepare('INSERT OR IGNORE INTO ai_approvals VALUES(?,?)').run(provider,identity(model,baseUrl));}
 guard(provider:string,model:string,baseUrl:string){if(!this.approved(provider,model,baseUrl))throw new ControlError(privacyNotice,'privacy_notice');}
 meter(provider:string){const now=this.clock(),day=new Date(now).toISOString().slice(0,10),s=this.settings(provider),u=this.db.prepare('SELECT COALESCE(sum(tokens),0) AS tokens,count(*) AS requests,COALESCE(sum(estimate),0) AS estimatedRequests FROM ai_debits WHERE provider=? AND day=?').get(provider,day) as any,r=this.db.prepare('SELECT count(*) AS n,min(at) AS oldest FROM ai_debits WHERE provider=? AND at>?').get(provider,now-60000) as any;return {...s,noPortfolio:!!s.noPortfolio,provider,day,...u,requestsLastMinute:r.n,remaining:s.dailyCap===null?null:Math.max(0,s.dailyCap-u.tokens),resetAt:new Date(Date.parse(day)+86400000).toISOString(),rateRetryAt:r.oldest===null?null:new Date(r.oldest+60000).toISOString(),method:'Conservative request bytes + maximum output, or higher reported usage; not a billing guarantee.'};}
 reserve(provider:string,body:any){const tokens=Buffer.byteLength(JSON.stringify(body),'utf8')+700,now=this.clock(),m=this.meter(provider);if(m.dailyCap!==null&&m.tokens+tokens>m.dailyCap){this.onCap();throw new ControlError('AI daily token cap reached for '+provider+'. Resets at '+m.resetAt+'. Increase the cap explicitly in Settings.','daily_cap');}if(m.rpm!==null&&m.requestsLastMinute>=m.rpm)throw new ControlError('AI request-rate limit reached for '+provider+'. Try after '+m.rateRetryAt+'.','rpm');const r=this.db.prepare('INSERT INTO ai_debits(provider,day,at,tokens,estimate) VALUES(?,?,?,?,1)').run(provider,m.day,now,tokens);return {id:Number(r.lastInsertRowid),tokens};}
 settle(reservation:{id:number,tokens:number},data:any){const u=data?.usage;const total=u?.total_tokens??(typeof u?.input_tokens==='number'&&typeof u?.output_tokens==='number'?u.input_tokens+u.output_tokens+(u.cache_creation_input_tokens??0)+(u.cache_read_input_tokens??0):null);if(Number.isSafeInteger(total)&&total>=0)this.db.prepare('UPDATE ai_debits SET tokens=max(tokens,?),estimate=0 WHERE id=?').run(total,reservation.id);}
}
