export type Bar=[number,number,number,number,number,number];
export type Spec={strategy:'hold'|'sma'|'trend'|'rsi',capital:number,feeBps:number,slippageBps:number,fast:number,slow:number,rsiPeriod:number,oversold:number,overbought:number};
export const defaults:Spec={strategy:'sma',capital:10000,feeBps:10,slippageBps:5,fast:5,slow:20,rsiPeriod:14,oversold:30,overbought:70};
export function validateSpec(s:Spec){if(!['hold','sma','trend','rsi'].includes(s.strategy))throw Error('Invalid strategy');for(const k of ['capital','feeBps','slippageBps','fast','slow','rsiPeriod','oversold','overbought'] as const)if(!Number.isFinite(s[k]))throw Error('Finite parameters required');if(s.capital<=0||s.capital>1e9||s.feeBps<0||s.feeBps>500||s.slippageBps<0||s.slippageBps>500)throw Error('Invalid capital or costs');if(![s.fast,s.slow,s.rsiPeriod].every(n=>Number.isInteger(n)&&n>=1&&n<=500)||s.fast>=s.slow||s.oversold<0||s.overbought>100||s.oversold>=s.overbought)throw Error('Invalid indicator parameters');}
export function backtest(bars:Bar[],partial:Partial<Spec>={}){const s={...defaults,...partial};validateSpec(s);if(bars.length<3||bars.length>10000)throw Error('Require 3 to 10000 closed bars');bars.forEach((b,i)=>{if(b.length!==6||!b.every(Number.isFinite)||b.slice(1,5).some(n=>n<=0)||b[2]<Math.max(b[1],b[4])||b[3]>Math.min(b[1],b[4])||b[5]<0||(i&&b[0]<=bars[i-1][0]))throw Error('Invalid OHLCV');});
function run(strategy:Spec['strategy']){let cash=s.capital,quantity=0,entryCost=0,fees=0,peak=s.capital,dd=0,lastSignal=false,avgGain=0,avgLoss=0;const fills:any[]=[],trades:any[]=[],equity:any[]=[];const mean=(end:number,n:number)=>bars.slice(end-n+1,end+1).reduce((a,b)=>a+b[4],0)/n;
for(let i=0;i<bars.length;i++){const b=bars[i];if(i>0&&lastSignal&&!quantity){const price=b[1]*(1+s.slippageBps/10000);quantity=cash/(price*(1+s.feeBps/10000));const fee=quantity*price*s.feeBps/10000;entryCost=cash;cash=0;fees+=fee;fills.push({side:'buy',time:b[0],price,quantity,fee,signalTime:bars[i-1][0]});}else if(i>0&&!lastSignal&&quantity){const price=b[1]*(1-s.slippageBps/10000),gross=quantity*price,fee=gross*s.feeBps/10000;cash=gross-fee;fees+=fee;trades.push({entry:fills[fills.length-1].time,exit:b[0],pnl:cash-entryCost});fills.push({side:'sell',time:b[0],price,quantity,fee,signalTime:bars[i-1][0]});quantity=0;}
const value=cash+quantity*b[4];peak=Math.max(peak,value);dd=Math.max(dd,(peak-value)/peak);equity.push({time:b[0],value});
if(strategy==='hold')lastSignal=true;
if(strategy==='sma')lastSignal=i+1>=s.slow&&mean(i,s.fast)>mean(i,s.slow);
if(strategy==='trend'&& (i===0||Math.floor(b[0]/604800000)!==Math.floor(bars[i-1][0]/604800000)))lastSignal=i>=7&&b[4]>bars[i-7][4];
if(strategy==='rsi'&&i>0){const delta=b[4]-bars[i-1][4];if(i<=s.rsiPeriod){avgGain+=Math.max(0,delta)/s.rsiPeriod;avgLoss+=Math.max(0,-delta)/s.rsiPeriod;}else{avgGain=(avgGain*(s.rsiPeriod-1)+Math.max(0,delta))/s.rsiPeriod;avgLoss=(avgLoss*(s.rsiPeriod-1)+Math.max(0,-delta))/s.rsiPeriod;}if(i>=s.rsiPeriod){const rsi=avgLoss===0?(avgGain===0?50:100):100-100/(1+avgGain/avgLoss);if(rsi<=s.oversold)lastSignal=true;else if(rsi>=s.overbought)lastSignal=false;}}
}
const wins=trades.filter(t=>t.pnl>0),loss=trades.filter(t=>t.pnl<0).reduce((a,t)=>a-t.pnl,0),profit=wins.reduce((a,t)=>a+t.pnl,0);return {equity,fills,trades,metrics:{netReturn:equity.at(-1).value/s.capital-1,maxDrawdown:dd,trades:trades.length,winRate:trades.length?wins.length/trades.length:0,profitFactor:loss?profit/loss:null,totalFees:fees,endingEquity:equity.at(-1).value,openPosition:quantity>0}};}
return {...run(s.strategy),baseline:run('hold'),parameters:s,assumptions:'Long-only spot, full equity, fractional quantities. Closed-bar signal; next-bar open fill. Weekly trend: daily bars, UTC epoch-week boundary, 7-day momentum. Final open position marked at last close, no forced exit. No funding, borrow, minimum-order rounding, liquidation or market impact beyond slippage. This is not a forecast.'};}
