import {type MarketRules,verifySnapshot,roundAmount,roundPrice,minimumReason,unknownRules} from './market-rules.js';
export type Bar=[number,number,number,number,number,number];
export type Spec={strategy:'hold'|'sma'|'trend'|'rsi',capital:number,feeBps:number,slippageBps:number,slippageModel:'flat'|'volume-volatility',fast:number,slow:number,rsiPeriod:number,oversold:number,overbought:number};
export type Context={rules?:MarketRules,warmupBars?:Bar[],intervalMs?:number};
export const defaults:Spec={strategy:'sma',capital:10000,feeBps:10,slippageBps:5,slippageModel:'flat',fast:5,slow:20,rsiPeriod:14,oversold:30,overbought:70};
export function validateSpec(s:Spec){if(!['hold','sma','trend','rsi'].includes(s.strategy)||!['flat','volume-volatility'].includes(s.slippageModel))throw Error('Invalid strategy or slippage model');for(const k of ['capital','feeBps','slippageBps','fast','slow','rsiPeriod','oversold','overbought'] as const)if(!Number.isFinite(s[k]))throw Error('Finite parameters required');if(s.capital<=0||s.capital>1e9||s.feeBps<0||s.feeBps>500||s.slippageBps<0||s.slippageBps>500)throw Error('Invalid capital or costs');if(![s.fast,s.slow,s.rsiPeriod].every(n=>Number.isInteger(n)&&n>=1&&n<=500)||s.fast>=s.slow||s.oversold<0||s.overbought>100||s.oversold>=s.overbought)throw Error('Invalid indicator parameters');}
export function warmupNeeded(s:Spec){return s.strategy==='hold'?1:s.strategy==='sma'?s.slow:s.strategy==='trend'?14:s.rsiPeriod+1;}
export const slippageFormula='flatBps + 10000 × population standard deviation of previous ≤20 closed-bar log returns × sqrt(requested base quantity / mean previous ≤20 closed-bar base volume). Entry request uses fee-reserved cash / unadjusted open. No cap; zero volume skips. This is an assumption, not order-book liquidity.';
export function slippageBps(s:Spec,history:Bar[],q:number){if(s.slippageModel==='flat')return s.slippageBps;const h=history.slice(-20),v=h.reduce((a,b)=>a+b[5],0)/h.length;if(!Number.isFinite(v)||v<=0)return null;const returns=h.slice(1).map((b,i)=>Math.log(b[4]/h[i][4]));const mean=returns.reduce((a,b)=>a+b,0)/(returns.length||1),sigma=Math.sqrt(returns.reduce((a,b)=>a+(b-mean)**2,0)/(returns.length||1));return s.slippageBps+10000*sigma*Math.sqrt(q/v);}
function validBars(bars:Bar[]){bars.forEach((b,i)=>{if(b.length!==6||!b.every(Number.isFinite)||b.slice(1,5).some(n=>n<=0)||b[2]<Math.max(b[1],b[4])||b[3]>Math.min(b[1],b[4])||b[5]<0||(i&&b[0]<=bars[i-1][0]))throw Error('Invalid OHLCV');});}
export function backtest(bars:Bar[],partial:Partial<Spec>={},ctx:Context={}){
 const s={...defaults,...partial};validateSpec(s);if(bars.length<3||bars.length>10000)throw Error('Require 3 to 10000 closed bars');const warm=ctx.warmupBars??[],all=[...warm,...bars],step=ctx.intervalMs??(bars[1][0]-bars[0][0]);validBars(all);if(ctx.rules)verifySnapshot(ctx.rules);if(ctx.intervalMs&&all.slice(1).some((b,i)=>b[0]-all[i][0]!==step))throw Error('Non-contiguous bar contract');
 function run(strategy:Spec['strategy']){let cash=s.capital,quantity=0,entryCost=0,fees=0,totalSlippage=0,peak=s.capital,dd=0,lastSignal=false,avgGain=0,avgLoss=0;const fills:any[]=[],trades:any[]=[],equity:any[]=[],rejections:any[]=[],signals:any[]=[];
 const mean=(end:number,n:number)=>all.slice(end-n+1,end+1).reduce((a,b)=>a+b[4],0)/n;
 for(let i=0;i<all.length;i++){const b=all[i],evaluating=i>=warm.length;
  if(evaluating&&i>0&&((lastSignal&&!quantity)||(!lastSignal&&quantity))){const side=lastSignal?'buy':'sell',request=side==='buy'?cash/(b[1]*(1+s.feeBps/10000)):quantity,bps=slippageBps(s,all.slice(Math.max(0,i-20),i),request);let reason=bps===null?'unavailable-volume':null,price=bps===null?b[1]:b[1]*(1+(side==='buy'?1:-1)*bps/10000),q=request;
   if(!reason&&price<=0)reason='non-positive-slipped-price';
   if(!reason&&ctx.rules){price=roundPrice(price,side,ctx.rules);if(price<=0)reason='rounded-price-zero';}
   if(!reason){q=side==='buy'?cash/(price*(1+s.feeBps/10000)):quantity;if(ctx.rules){q=roundAmount(q,ctx.rules);reason=minimumReason(q,price,ctx.rules);}if(q<=0)reason='rounded-to-zero';if(q>request&&side==='buy')throw Error('Rounding created quantity');}
   const gross=q*price,fee=gross*s.feeBps/10000;
   if(!reason&&side==='buy'&&gross+fee>cash){if(gross+fee-cash<=Math.max(1,cash)*1e-12){q=ctx.rules?roundAmount(q*(1-1e-12),ctx.rules):q*(1-1e-12);reason=ctx.rules?minimumReason(q,price,ctx.rules):null;}else reason='insufficient-cash';}
   if(reason)rejections.push({side,time:b[0],signalTime:all[i-1][0]+step,signalBarOpen:all[i-1][0],reason,requestedQuantity:request,roundedQuantity:q,price});
   else {const notional=q*price,paid=notional*s.feeBps/10000,slip=q*Math.abs(price-b[1]),before=cash;
    if(side==='buy'){entryCost=notional+paid;cash-=entryCost;quantity=q;}else{cash+=notional-paid;const share=q/quantity;trades.push({entry:[...fills].reverse().find(f=>f.side==='buy')?.time,exit:b[0],pnl:notional-paid-entryCost*share});entryCost*=1-share;quantity=Math.max(0,quantity-q);}
    if(cash<0||quantity<0)throw Error('Negative spot ledger');fees+=paid;totalSlippage+=slip;fills.push({side,time:b[0],signalTime:all[i-1][0]+step,signalBarOpen:all[i-1][0],phase:'closed signal → next open',price,open:b[1],quantity:q,requestedQuantity:request,fee:paid,feeSide:'taker',feeCurrency:'quote',slippage:slip,slippageBps:bps,cashBefore:before,cashAfter:cash});
   }
  }
  if(evaluating){const value=cash+quantity*b[4];peak=Math.max(peak,value);dd=Math.max(dd,(peak-value)/peak);equity.push({time:b[0],value,cash,quantity,close:b[4],positionValue:quantity*b[4],fees,slippage:totalSlippage});}
  if(strategy==='hold')lastSignal=true;
  if(strategy==='sma')lastSignal=i+1>=s.slow&&mean(i,s.fast)>mean(i,s.slow);
  if(strategy==='trend'&&(i===0||Math.floor(b[0]/604800000)!==Math.floor(all[i-1][0]/604800000)))lastSignal=i>=7&&b[4]>all[i-7][4];
  if(strategy==='rsi'&&i>0){const delta=b[4]-all[i-1][4];if(i<=s.rsiPeriod){avgGain+=Math.max(0,delta)/s.rsiPeriod;avgLoss+=Math.max(0,-delta)/s.rsiPeriod;}else{avgGain=(avgGain*(s.rsiPeriod-1)+Math.max(0,delta))/s.rsiPeriod;avgLoss=(avgLoss*(s.rsiPeriod-1)+Math.max(0,-delta))/s.rsiPeriod;}if(i>=s.rsiPeriod){const rsi=avgLoss===0?(avgGain===0?50:100):100-100/(1+avgGain/avgLoss);if(rsi<=s.oversold)lastSignal=true;else if(rsi>=s.overbought)lastSignal=false;}}
  if(evaluating)signals.push({barOpen:b[0],availableAt:b[0]+step,long:lastSignal});
 }
 const wins=trades.filter(t=>t.pnl>0),loss=trades.filter(t=>t.pnl<0).reduce((a,t)=>a-t.pnl,0),profit=wins.reduce((a,t)=>a+t.pnl,0);return {equity,fills,trades,rejections,signals,metrics:{netReturn:equity.at(-1).value/s.capital-1,maxDrawdown:dd,trades:trades.length,winRate:trades.length?wins.length/trades.length:0,profitFactor:loss?profit/loss:null,totalFees:fees,totalSlippage,skippedOrders:rejections.length,endingCash:cash,endingQuantity:quantity,endingEquity:equity.at(-1).value,openPosition:quantity>0}};
 }
 return {...run(s.strategy),baseline:run('hold'),parameters:s,warmup:{required:warmupNeeded(s),available:warm.length,policy:'Pre-range bars initialise indicators only; no pre-range fills or equity. Insufficient history remains cash until a valid closed-bar signal.'},model:{rules:ctx.rules??null,unknownConstraints:ctx.rules?unknownRules(ctx.rules):['legacy fractional model'],slippage:s.slippageModel,formula:s.slippageModel==='flat'?'Adverse flat bps on every fill.':slippageFormula,barContract:'Closed-bar signal → next open. Equal timestamp phase order: close, decision, fill. Zero delay assumption; not an observed executable quote.',omitted:['Order-book depth','Partial fills','Latency','Funding (spot)','Taxes','Outages','Historical changes to rules and account fee tiers']},assumptions:`Long-only spot; fee-reserved sizing, residual cash retained. ${ctx.rules?'Current exchange rules applied historically; amounts truncated, prices rounded adversely; unknown constraints remain unverified.':'Legacy fractional model: exchange feasibility unverified.'} Taker fees in quote currency. Closed-bar signal; next-open fill. Pre-range history only initialises indicators. Weekly trend: daily bars, UTC epoch-week boundary, 7-day momentum. Final open position marked at last close; no forced disposal. This is past behaviour, not a forecast.`};
}
