import type {DatabaseSync} from 'node:sqlite';
import {version} from './common.js';
import {hash,verifySnapshot,type MarketRules} from './market-rules.js';
import {versusBTC} from './benchmark.js';
import type {Bar,Spec} from './backtest.js';
export const engineVersion='spot-next-open-2';
export type Bundle={asset:Bar[],btc:Bar[],warmup:Bar[],btcWarmup:Bar[],rules:MarketRules,btcRules:MarketRules|null,parameters:Spec,btcFeeBps:number,feeMode:'exchange'|'override',exchange:string,symbol:string,timeframe:string,intervalMs:number,start:number,end:number,coverage:any,baselineSymbol:string,quoteIsBTC:boolean,protocol?:any};
export function manifest(b:Bundle){return {schema:1,...(b.protocol?{evaluationProtocol:b.protocol}:{}),appVersion:version,engineVersion,dataSource:b.exchange,symbol:b.symbol,timeframe:b.timeframe,range:{requestedStart:b.start,requestedEnd:b.end,actualStart:b.asset[0][0],actualEnd:b.asset.at(-1)![0]+b.intervalMs},candleDataHash:hash(b.asset),warmupDataHash:hash(b.warmup),btcDataHash:hash(b.btc),btcWarmupDataHash:hash(b.btcWarmup),marketRulesHash:b.rules.hash,btcMarketRulesHash:b.btcRules?.hash??null,fee:{mode:b.feeMode,side:'taker',currency:'quote',bps:b.parameters.feeBps,btcBps:b.btcFeeBps,source:b.feeMode==='override'?'User override':b.rules.feeSource,date:b.rules.feeDate},slippage:{model:b.parameters.slippageModel,bps:b.parameters.slippageBps},strategyParameters:b.parameters,barContract:'close → decision → next open',bundleHash:hash(b)};}
export function evaluate(b:Bundle){verifySnapshot(b.rules);if(b.btcRules)verifySnapshot(b.btcRules);const tested=versusBTC(b.asset,b.btc,b.parameters,b.quoteIsBTC,{rules:b.rules,warmupBars:b.warmup,intervalMs:b.intervalMs},{rules:b.btcRules??undefined,warmupBars:b.btcWarmup,intervalMs:b.intervalMs},b.btcFeeBps);return {...tested,coverage:b.coverage,symbol:b.symbol,timeframe:b.timeframe,baselineSymbol:b.baselineSymbol,manifest:manifest(b),benchmarkRules:b.btcRules};}
export function differences(a:any,b:any,path=''):string[]{if(hash(a)===hash(b))return [];if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b))return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>differences(a[k]??null,b[k]??null,path?path+'.'+k:k));return [path||'result'];}
export class BenchRuns {constructor(private db:DatabaseSync,private require:(source:string)=>void){db.exec('CREATE TABLE IF NOT EXISTS bench_runs(id INTEGER PRIMARY KEY,bundle TEXT NOT NULL,result TEXT NOT NULL,digest TEXT NOT NULL,created TEXT NOT NULL)');}
 save(b:Bundle){this.require(b.exchange);const result=evaluate(b),created=new Date().toISOString(),digest=hash(result);this.require(b.exchange);const row=this.db.prepare('INSERT INTO bench_runs(bundle,result,digest,created) VALUES(?,?,?,?)').run(JSON.stringify(b),JSON.stringify(result),digest,created);return {...result,runId:Number(row.lastInsertRowid),resultDigest:digest,savedAt:created};}
 bundle(id:number):Bundle{const saved=this.get(id),row=this.db.prepare('SELECT bundle FROM bench_runs WHERE id=?').get(id) as any,b:Bundle=JSON.parse(row.bundle);this.require(b.exchange);if(hash(b)!==saved.manifest.bundleHash)throw Error('Bundle integrity mismatch');return b;}
 get(id:number){if(!Number.isSafeInteger(id)||id<=0)throw Error('Invalid run');const row=this.db.prepare('SELECT id,result,digest,created FROM bench_runs WHERE id=?').get(id) as any;if(!row)throw Error('Run unavailable');const r=JSON.parse(row.result);this.require(r.manifest.dataSource);if(hash(r)!==row.digest)throw Error('Result integrity mismatch');return {...r,runId:row.id,resultDigest:row.digest,savedAt:row.created};}
 list(){return (this.db.prepare('SELECT id FROM bench_runs ORDER BY id DESC LIMIT 200').all() as any[]).flatMap(row=>{try{const r=this.get(row.id);return [{runId:r.runId,savedAt:r.savedAt,symbol:r.symbol,strategy:r.parameters.strategy,manifest:r.manifest}];}catch{return [];}});}
 compare(ids:number[]){if(!Array.isArray(ids)||ids.length<2||ids.length>4||new Set(ids).size!==ids.length)throw Error('Choose 2 to 4 different runs');return ids.map(id=>this.get(id));}
 latest(){const row=this.db.prepare('SELECT id,result,digest,created FROM bench_runs ORDER BY id DESC LIMIT 1').get() as any;if(!row)return null;const r=JSON.parse(row.result);this.require(r.manifest.dataSource);return {...r,runId:row.id,resultDigest:row.digest,savedAt:row.created};}
 replay(id:number){if(!Number.isSafeInteger(id)||id<=0)throw Error('Invalid run');const row=this.db.prepare('SELECT * FROM bench_runs WHERE id=?').get(id) as any;if(!row)throw Error('Run unavailable');const b:Bundle=JSON.parse(row.bundle),saved=JSON.parse(row.result);this.require(b.exchange);if(hash(b)!==saved.manifest.bundleHash)throw Error('Bundle integrity mismatch');const current=evaluate(b);const diffs=differences(saved,current);this.require(b.exchange);return {status:diffs.length?'different':'identical',differences:diffs,savedDigest:row.digest,replayedDigest:hash(current),savedVersion:saved.manifest.appVersion,currentVersion:version,result:{...current,runId:id,resultDigest:hash(current),savedAt:row.created}};}
}
