import type {DatabaseSync} from 'node:sqlite';
import {hash} from './market-rules.js';
export type Window={exchange:string,symbol:string,timeframe:string,start:number,end:number};
const overlap=(a:Window,b:Window)=>a.exchange===b.exchange&&a.symbol===b.symbol&&a.start<b.end&&a.end>b.start;
export class Holdouts{
 constructor(private db:DatabaseSync,private require:(source:string)=>void){db.exec(`CREATE TABLE IF NOT EXISTS holdouts(id INTEGER PRIMARY KEY,identity TEXT UNIQUE NOT NULL,config TEXT NOT NULL,tuning_id INTEGER NOT NULL,sealed_id INTEGER,state TEXT NOT NULL,seen INTEGER NOT NULL,created TEXT NOT NULL,unsealed TEXT); CREATE TABLE IF NOT EXISTS inspected_windows(id INTEGER PRIMARY KEY,config TEXT NOT NULL,inspected TEXT NOT NULL)`);}
 private row(id:number){if(!Number.isSafeInteger(id)||id<1)throw Error('Invalid experiment');const r=this.db.prepare('SELECT * FROM holdouts WHERE id=?').get(id) as any;if(!r)throw Error('Experiment unavailable');this.require(JSON.parse(r.config).exchange);return r;}
 private seen(w:Window){const prior=this.db.prepare('SELECT config FROM inspected_windows').all() as any[];const saved=this.db.prepare('SELECT result FROM bench_runs').all() as any[];return prior.some(r=>overlap(w,JSON.parse(r.config)))||saved.some(r=>{const m=JSON.parse(r.result).manifest;return overlap(w,{exchange:m.dataSource,symbol:m.symbol,timeframe:m.timeframe,start:m.range.actualStart,end:m.range.actualEnd});});}
 guard(w:Window){const active=this.db.prepare("SELECT config FROM holdouts WHERE state IN ('sealed','unsealing')").all() as any[];if(active.some(r=>{const c=JSON.parse(r.config);return overlap(w,{...c,start:c.split});}))throw Error('Sealed window: use explicit unseal once, not the ordinary bench or AI.');}
 observe(w:Window){this.require(w.exchange);this.db.prepare('INSERT INTO inspected_windows(config,inspected) VALUES(?,?)').run(JSON.stringify(w),new Date().toISOString());}
 retest(w:Window){const previous=(this.db.prepare("SELECT identity,config,unsealed FROM holdouts WHERE state='unsealed'").all() as any[]).filter(r=>{const c=JSON.parse(r.config);return overlap(w,{...c,start:c.split});});return previous.length?{role:'seen-window-retest',seen:true,priorExperiments:previous.map(r=>r.identity),notice:'This window has already been inspected; later parameter changes are seen, not fresh out-of-sample evidence.'}:null;}
 async create(config:any,run:(config:any)=>Promise<any>){this.require(config.exchange);if(!Number.isFinite(config.start)||!Number.isFinite(config.end)||!Number.isFinite(config.split)||config.split<=config.start||config.split>=config.end)throw Error('Disjoint chronological windows required');const interval=({ '1h':3600000,'4h':14400000,'1d':86400000} as any)[config.timeframe];if(!interval||[config.start,config.split,config.end].some(t=>t%interval)||(config.split-config.start)/interval<3||(config.end-config.split)/interval<3)throw Error('Aligned windows of at least three bars required');const identity=hash(config),existing=this.db.prepare('SELECT id FROM holdouts WHERE identity=?').get(identity) as any;if(existing)return this.get(existing.id);const seen=this.seen({...config,start:config.split});const tuning=await run({...config,end:config.split,_protocol:{identity,role:'tuning',seen,split:config.split,sealedEnd:config.end}});this.require(config.exchange);const created=new Date().toISOString();const r=this.db.prepare("INSERT INTO holdouts(identity,config,tuning_id,state,seen,created) VALUES(?,?,?,'sealed',?,?)").run(identity,JSON.stringify(config),tuning.runId,seen?1:0,created);return this.get(Number(r.lastInsertRowid));}
 get(id:number){const r=this.row(id),c=JSON.parse(r.config),seen=!!r.seen||(r.state!=='unsealed'&&this.seen({...c,start:c.split}));return {id:r.id,identity:r.identity,config:c,tuningRunId:r.tuning_id,sealedRunId:r.state==='unsealed'?r.sealed_id:null,state:r.state,seen,created:r.created,unsealedAt:r.unsealed??null,capitalPolicy:'Independent starting capital in each window; preceding indicators only, no tuning inventory or equity carried.',notice:seen?'Seen window: prior access or parameter revision means this is not untouched out-of-sample evidence.':'Locally sealed workflow only. The owner can inspect the database or public market history; no cryptographic guarantee.'};}
 list(){return (this.db.prepare('SELECT id FROM holdouts ORDER BY id DESC LIMIT 200').all() as any[]).flatMap(r=>{try{return [this.get(r.id)];}catch{return [];}});}
 async unseal(id:number,run:(config:any)=>Promise<any>){const r=this.row(id);if(r.state==='unsealed')return this.get(id);if(r.state!=='sealed')throw Error('Already evaluating');const c=JSON.parse(r.config),seen=!!r.seen||this.seen({...c,start:c.split});const updated=this.db.prepare("UPDATE holdouts SET state='unsealing' WHERE id=? AND state='sealed'").run(id);if(!updated.changes)throw Error('Already evaluating');try{const sealed=await run({...c,start:c.split,_frozenFrom:r.tuning_id,_protocol:{identity:r.identity,role:'unsealed',seen,split:c.split,sealedEnd:c.end,inspectionStarted:new Date().toISOString()}});this.require(c.exchange);const now=new Date().toISOString();this.db.prepare("UPDATE holdouts SET state='unsealed',sealed_id=?,unsealed=?,seen=? WHERE id=?").run(sealed.runId,now,seen?1:0,id);this.observe({...c,start:c.split});return this.get(id);}catch(error){this.db.prepare("UPDATE holdouts SET state='sealed' WHERE id=? AND state='unsealing'").run(id);throw error;}}
 annotation(runId:number){const r=this.db.prepare('SELECT id FROM holdouts WHERE tuning_id=? OR sealed_id=?').get(runId,runId) as any;if(!r)return null;const e=this.get(r.id);return {...e,role:e.tuningRunId===runId?'tuning':'unsealed',sealedRunId:e.state==='unsealed'?e.sealedRunId:null};}
}
