import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import ccxt from 'ccxt';
import {backtest,defaults,type Bar,type Spec,slippageBps} from './backtest.js';import {snapshot,hash,roundAmount,roundPrice,type MarketRules} from './market-rules.js';import {BenchRuns,evaluate,differences,type Bundle} from './bench-run.js';import {database} from './common.js';import {Market} from './market.js';
const bars=(n=70):Bar[]=>Array.from({length:n},(_,i)=>{const c=10+Math.sin(i/3)*3+i/20,o=10+Math.sin((i-1)/3)*3+i/20;return [i*86400000,o,Math.max(c,o)+1,Math.min(c,o)-1,c,100];});
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<=Math.max(1,Math.abs(a),Math.abs(b))*1e-10,`${a} != ${b}`);
function rules(p:any={}):MarketRules{const r=snapshot({precisionMode:ccxt.TICK_SIZE},{spot:true,symbol:'FIX/USD',precision:{amount:.01,price:.1},limits:{amount:{min:.01},cost:{min:1}},maker:.001,taker:.002},'synthetic','2026-10-07T17:00:00Z');const {hash:_,...body}=r;return {...body,...p,hash:hash({...body,...p})};}
const strategies:Spec['strategy'][]=['hold','sma','trend','rsi'];
for(const strategy of strategies)for(const model of ['flat','volume-volatility'] as const){
 test(`SYNTHETIC ${strategy}/${model}: all-prefix and future mutation causal contract`,()=>{const b=bars(),p={strategy,slippageModel:model,fast:2,slow:5,rsiPeriod:3,oversold:45,overbought:55};const full=backtest(b,p,{rules:rules(),intervalMs:86400000});for(let k=3;k<b.length;k++){const prefix=backtest(b.slice(0,k),p,{rules:rules(),intervalMs:86400000});assert.deepEqual(prefix.equity,full.equity.slice(0,k));assert.deepEqual(prefix.signals,full.signals.slice(0,k));const mutated=b.map((v,i)=>i<k?v:[v[0],100,1000,1,500,1] as Bar);const m=backtest(mutated,p,{rules:rules(),intervalMs:86400000});assert.deepEqual(m.equity.slice(0,k),prefix.equity);assert.deepEqual(m.fills.filter(f=>f.time<b[k][0]),prefix.fills);assert.deepEqual(m.rejections.filter(f=>f.time<b[k][0]),prefix.rejections);}for(const f of full.fills){assert.equal(f.signalTime,f.time);assert.equal(f.signalBarOpen+86400000,f.time);}});
 test(`SYNTHETIC ${strategy}/${model}: accounting matrix tiny/normal capital and costs`,()=>{for(const capital of [.01,10,10000])for(const feeBps of [0,100]){const r=backtest(bars(),{strategy,slippageModel:model,capital,feeBps,slippageBps:10,fast:2,slow:5,rsiPeriod:3,oversold:45,overbought:55},{rules:rules()});for(const p of r.equity){near(p.value,p.cash+p.quantity*p.close);assert.ok(p.cash>=0&&p.quantity>=0);near(p.fees,r.fills.filter(f=>f.time<=p.time).reduce((a,f)=>a+f.fee,0));near(p.slippage,r.fills.filter(f=>f.time<=p.time).reduce((a,f)=>a+f.slippage,0));}near(r.metrics.totalFees,r.fills.reduce((a,f)=>a+f.fee,0));near(r.metrics.totalSlippage,r.fills.reduce((a,f)=>a+f.slippage,0));for(const f of r.fills){assert.ok(f.side==='buy'?f.price>=f.open:f.price<=f.open);assert.ok(f.quantity<=f.requestedQuantity+1e-12);near(f.cashAfter,f.cashBefore+(f.side==='buy'?-1:1)*f.quantity*f.price-f.fee);}}});
}
for(const strategy of strategies)test(`SYNTHETIC ${strategy}: warm-up excluded and fills require valid prior closed signal`,()=>{const b=bars(35),p={strategy,fast:1,slow:5,rsiPeriod:3,oversold:100-1,overbought:100};const r=backtest(b.slice(20),p,{rules:rules(),warmupBars:b.slice(0,20),intervalMs:86400000});assert.equal(r.equity.length,15);assert.ok(r.fills.every(f=>f.time>=b[20][0]));assert.equal(r.equity[0].time,b[20][0]);assert.equal(r.warmup.available,20);const short=backtest(b.slice(0,3),{...p,slow:10,rsiPeriod:10});if(strategy!=='hold')assert.equal(short.fills.length,0);const full=backtest(b.slice(20),p,{rules:rules(),warmupBars:b.slice(0,20),intervalMs:86400000});assert.deepEqual(r,full);});
test('SYNTHETIC precision modes truncate quantities and round prices adversely',()=>{for(const p of [{precisionMode:ccxt.TICK_SIZE,amountPrecision:.05,pricePrecision:.25},{precisionMode:ccxt.DECIMAL_PLACES,amountPrecision:2,pricePrecision:2},{precisionMode:ccxt.SIGNIFICANT_DIGITS,amountPrecision:3,pricePrecision:3}]){const r=rules(p);for(const q of [.000123456,.999999,12.345,1234.567])assert.ok(roundAmount(q,r)<=q);for(const price of [.000123456,.999999,12.345,1234.567]){assert.ok(roundPrice(price,'buy',r)>=price);if(price>=.25)assert.ok(roundPrice(price,'sell',r)<=price);}}});
test('SYNTHETIC hand arithmetic, residual cash and below-minimum attempts spend nothing',()=>{const b=Array.from({length:4},(_,i)=>[i*86400000,10,10,10,10,100] as Bar),r=backtest(b,{strategy:'hold',capital:101,feeBps:100,slippageBps:0},{rules:rules({amountPrecision:1,pricePrecision:1})});assert.equal(r.fills[0].quantity,10);near(r.fills[0].fee,1);near(r.metrics.endingCash,0);near(r.metrics.endingEquity,100);for(const constraints of [{minAmount:11,minCost:0},{minAmount:0,minCost:110}]){const rejected=backtest(b,{strategy:'hold',capital:100,feeBps:0,slippageBps:0},{rules:rules(constraints)});assert.equal(rejected.fills.length,0);assert.equal(rejected.metrics.skippedOrders,3);assert.equal(rejected.metrics.endingEquity,100);assert.equal(rejected.metrics.totalFees,0);}});
test('SYNTHETIC exit dust is retained; fee/slippage losses are not reminted',()=>{const b=[10,20,30,10,5,10].map((p,i)=>[i*86400000,p,p,p,p,100] as Bar),r=backtest(b,{capital:100,fast:1,slow:2,feeBps:0,slippageBps:0},{rules:rules({amountPrecision:1,minCost:50})});assert.equal(r.fills.length,1);assert.ok(r.rejections.some(x=>x.side==='sell'&&x.reason==='below-minimum-cost'));assert.ok(r.metrics.endingQuantity>0);});
test('SYNTHETIC volume model uses prior bars and zero volume skips',()=>{assert.equal(slippageBps({...defaults,slippageModel:'volume-volatility'},bars(5).map(x=>[...x.slice(0,5),0] as Bar),1),null);const r=backtest(bars(5).map(x=>[...x.slice(0,5),0] as Bar),{strategy:'hold',slippageModel:'volume-volatility'},{rules:rules()});assert.equal(r.fills.length,0);assert.ok(r.rejections.every(x=>x.reason==='unavailable-volume'));});
const recordings=JSON.parse(readFileSync('tests/fixtures/market-rules-recorded-20261007.json','utf8'));
for(const rec of recordings)test(`RECORDED ${rec.exchange} public ccxt market ${rec.capturedAt}`,()=>{assert.equal(rec.label,'recorded');const r=snapshot(rec.adapter,rec.market,rec.exchange,rec.capturedAt);const result=backtest(bars(10),{strategy:'hold',capital:.00001},{rules:r});assert.equal(result.fills.length,0);assert.ok(result.metrics.skippedOrders>0);assert.equal(r.hash,hash(Object.fromEntries(Object.entries(r).filter(([k])=>k!=='hash'))));});
function bundle():Bundle{const b=bars();return {asset:b.slice(20),btc:b.slice(20),warmup:b.slice(0,20),btcWarmup:b.slice(0,20),rules:rules(),btcRules:rules({symbol:'BTC/USD',amountPrecision:.001}),parameters:{...defaults,fast:2,slow:5},btcFeeBps:20,feeMode:'exchange',exchange:'synthetic',symbol:'FIX/USD',timeframe:'1d',intervalMs:86400000,start:b[20][0],end:b.at(-1)![0]+86400000,coverage:{exchange:'synthetic',source:'synthetic'},baselineSymbol:'BTC/USD',quoteIsBTC:false};}
test('SYNTHETIC immutable bundle replay after DB reopen; source revocation and integrity gates',()=>{const dir=mkdtempSync(join(tmpdir(),'bench-')),path=join(dir,'app.sqlite');let enabled=true,db=database(path),runs=new BenchRuns(db,()=>{if(!enabled)throw Error('Disabled');});try{const b=bundle(),saved=runs.save(b);b.asset[0][4]+=1;assert.equal(runs.replay(saved.runId).status,'identical');db.close();db=database(path);runs=new BenchRuns(db,()=>{if(!enabled)throw Error('Disabled');});assert.equal(runs.replay(saved.runId).status,'identical');enabled=false;assert.throws(()=>runs.latest());assert.throws(()=>runs.replay(saved.runId));enabled=true;const row=db.prepare('SELECT bundle FROM bench_runs').get() as any,changed=JSON.parse(row.bundle);changed.parameters.feeBps+=1;db.prepare('UPDATE bench_runs SET bundle=?').run(JSON.stringify(changed));assert.throws(()=>runs.replay(saved.runId),/integrity/);}finally{db.close();rmSync(dir,{recursive:true});}});
test('SYNTHETIC manifest identity reacts to candles, rules, parameters and model; reports differences',()=>{const b=bundle(),a=evaluate(b);for(const change of [(x:Bundle)=>x.parameters.feeBps++,(x:Bundle)=>x.parameters.slippageModel='volume-volatility',(x:Bundle)=>x.rules=rules({minCost:5}),(x:Bundle)=>x.asset[0][5]++]){const x=structuredClone(b);change(x);const r=evaluate(x);assert.notEqual(r.manifest.bundleHash,a.manifest.bundleHash);assert.ok(differences(a,r).length>0);}assert.notEqual(a.manifest.marketRulesHash,a.manifest.btcMarketRulesHash);});
test('SYNTHETIC market rules source gate refuses before any exchange call',async()=>{const db=database(':memory:');let calls=0;const m=new Market(db,{require:()=>{calls++;throw Error('Disabled');}});await assert.rejects(()=>m.rules('kraken','BTC/USD'));assert.equal(calls,1);db.close();});
