import ccxt from 'ccxt';
import {createHash} from 'node:crypto';
export function canonical(value:any):string {if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).filter(k=>value[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
export const hash=(v:any)=>createHash('sha256').update(canonical(v)).digest('hex');
export type MarketRules={schema:1,exchange:string,symbol:string,capturedAt:string,source:string,ccxtVersion:string,precisionMode:number,amountPrecision:number|null,pricePrecision:number|null,minAmount:number|null,minCost:number|null,maxAmount:number|null,maxCost:number|null,minPrice:number|null,maxPrice:number|null,maker:number|null,taker:number|null,feeSource:string,feeDate:string,ccxtMaker:number|null,ccxtTaker:number|null,feeCaptureHash:string|null,hash:string};
const finite=(x:any)=>typeof x==='number'&&Number.isFinite(x)&&x>=0?x:null;
const precision=(x:any,mode:number)=>typeof x==='number'&&Number.isFinite(x)&&(mode===ccxt.TICK_SIZE?x>0:mode===ccxt.SIGNIFICANT_DIGITS?Number.isInteger(x)&&x>0:Number.isInteger(x))?x:null;
export function snapshot(ex:any,m:any,exchange:string,capturedAt=new Date().toISOString()):MarketRules {if(!m?.spot||!m.symbol)throw Error('Spot market metadata required');const r:any={schema:1,exchange,symbol:m.symbol,capturedAt,source:`ccxt ${ccxt.version} loadMarkets public ${exchange}`,ccxtVersion:ccxt.version,precisionMode:ex.precisionMode,amountPrecision:precision(m.precision?.amount,ex.precisionMode),pricePrecision:precision(m.precision?.price,ex.precisionMode),minAmount:finite(m.limits?.amount?.min),minCost:finite(m.limits?.cost?.min),maxAmount:finite(m.limits?.market?.max??m.limits?.amount?.max),maxCost:finite(m.limits?.cost?.max),minPrice:finite(m.limits?.price?.min),maxPrice:finite(m.limits?.price?.max),maker:finite(m.maker??ex.fees?.trading?.maker),taker:finite(m.taker??ex.fees?.trading?.taker),feeSource:`ccxt ${ccxt.version} market/adapter fee metadata (not an account fee quote; may be outdated)`,feeDate:capturedAt,ccxtMaker:finite(m.maker??ex.fees?.trading?.maker),ccxtTaker:finite(m.taker??ex.fees?.trading?.taker),feeCaptureHash:null};
// Independently captured published general-spot schedule, not an account entitlement.
// Narrow applicability: known ordinary crypto bases only; special/unknown pairs keep ccxt metadata.
if(exchange==='kraken'&&['BTC','ETH','SOL'].includes(m.symbol.split('/')[0])){r.maker=.004;r.taker=.008;r.feeSource='https://www.kraken.com/features/fee-schedule · published general spot tier 1, captured 2026-10-07 (ccxt defaults differ; verify pair/region/account tier)';r.feeDate='2026-10-07T19:43:32+02:00';r.feeCaptureHash='d645a82958d510e952e0078ece90c2305030780e7eed2d5ceab0855afb866e98';}return {...r,hash:hash(r)};}
export function verifySnapshot(r:MarketRules){const {hash:h,...body}=r;if(hash(body)!==h)throw Error('Market snapshot hash mismatch');if(![ccxt.DECIMAL_PLACES,ccxt.TICK_SIZE,ccxt.SIGNIFICANT_DIGITS].includes(r.precisionMode)||r.amountPrecision===null||r.pricePrecision===null)throw Error('Amount/price precision unavailable; feasibility unverified');}
export function roundAmount(q:number,r:MarketRules){return Number(ccxt.decimalToPrecision(String(q),ccxt.TRUNCATE,r.amountPrecision!,r.precisionMode));}
export function roundPrice(p:number,side:'buy'|'sell',r:MarketRules){let v=Number(ccxt.decimalToPrecision(String(p),ccxt.TRUNCATE,r.pricePrecision!,r.precisionMode));if(side==='buy'&&v<p){const step=r.precisionMode===ccxt.TICK_SIZE?r.pricePrecision!:r.precisionMode===ccxt.DECIMAL_PLACES?10**(-r.pricePrecision!):10**(Math.floor(Math.log10(p))-r.pricePrecision!+1);v=Number(ccxt.decimalToPrecision(ccxt.Precise.stringAdd(String(v),String(step)),ccxt.ROUND,r.pricePrecision!,r.precisionMode));}if(!Number.isFinite(v)||v<0||(side==='buy'&&v<p)||(side==='sell'&&v>p))throw Error('Invalid price rounding');return v;}
export function minimumReason(q:number,p:number,r:MarketRules){if(q<=0)return 'rounded-to-zero';if(r.minAmount!==null&&q<r.minAmount)return 'below-minimum-amount';if(r.minCost!==null&&q*p<r.minCost)return 'below-minimum-cost';if(r.maxAmount!==null&&q>r.maxAmount)return 'above-maximum-amount';if(r.maxCost!==null&&q*p>r.maxCost)return 'above-maximum-cost';if(r.minPrice!==null&&p<r.minPrice)return 'below-minimum-price';if(r.maxPrice!==null&&p>r.maxPrice)return 'above-maximum-price';return null;}
export const unknownRules=(r:MarketRules)=>['minAmount','minCost','maxAmount','maxCost'].filter(k=>(r as any)[k]===null);
