import type {DatabaseSync} from 'node:sqlite';
import nodemailer from 'nodemailer';import {resolveOutbound} from './outbound.js';import {ControlError} from './ai-controls.js';
export const eventMessages:Record<string,string>={worker_finished:'CryptoTools: a worker job finished.',worker_failed:'CryptoTools: a worker job failed.',ai_cap:'CryptoTools: an AI daily cap was reached.',source_failed:'CryptoTools: a data source check failed.',update_available:'CryptoTools: an app update is available.',unsealed:'CryptoTools: a sealed window was opened.',test:'CryptoTools: test notification.'};
export const notificationEvents=Object.keys(eventMessages).filter(k=>k!=='test');
type Crypt={encrypt:(s:string)=>string,decrypt:(s:string)=>string};
export async function deliver(channel:string,c:any,message:string){
 if(channel==='telegram'){const r=await fetch('https://api.telegram.org/bot'+c.token+'/sendMessage',{method:'POST',redirect:'error',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:c.chatId,text:message,disable_notification:true}),signal:AbortSignal.timeout(10000)});if(!r.ok||(await r.json() as any).ok!==true)throw Error('Delivery failed');}
 else {if(c.allowPrivate&&process.env.CRYPTOTOOLS_SANDBOX==='1')throw new ControlError('Local/private SMTP is unavailable in sandbox mode.','outbound_refused');const address=await resolveOutbound(c.host,{allowPrivate:c.allowPrivate===true});const t=nodemailer.createTransport({host:address.address,port:c.port,secure:c.secure,requireTLS:!c.secure,auth:c.user?{user:c.user,pass:c.password}:undefined,tls:{rejectUnauthorized:true,servername:c.host.replace(/^\[|\]$/g,'')},connectionTimeout:10000,socketTimeout:10000,logger:false,debug:false});try{await t.sendMail({from:c.from,to:c.to,subject:'CryptoTools status',text:message,disableFileAccess:true,disableUrlAccess:true});}finally{t.close();}}
}
export class Notifications {
 constructor(private db:DatabaseSync,private crypt:Crypt,readonly sandbox=process.env.CRYPTOTOOLS_SANDBOX==='1',private send=deliver,private clock=Date.now,private guard:(text:string)=>void=()=>{}){db.exec(`CREATE TABLE IF NOT EXISTS notification_channels(channel TEXT PRIMARY KEY,enabled INTEGER NOT NULL,events TEXT NOT NULL,cipher TEXT,status TEXT); CREATE TABLE IF NOT EXISTS notification_attempts(channel TEXT,at INTEGER,event TEXT,dedupe TEXT); CREATE UNIQUE INDEX IF NOT EXISTS notification_dedupe ON notification_attempts(channel,dedupe) WHERE dedupe IS NOT NULL`);}
 list(){return {sandbox:this.sandbox,events:notificationEvents,channels:['telegram','email'].map(channel=>{const r=this.row(channel);return {channel,enabled:!!r?.enabled,events:r?JSON.parse(r.events):[],configured:!!r?.cipher,status:r?.status??'Off; supply your own channel.',allowPrivate:channel==='email'&&!!r?.cipher&&JSON.parse(this.crypt.decrypt(r.cipher)).allowPrivate===true};})};}
 private row(channel:string){if(!['telegram','email'].includes(channel))throw Error('Invalid channel');return this.db.prepare('SELECT * FROM notification_channels WHERE channel=?').get(channel) as any;}
 update(channel:string,b:any){const old=this.row(channel);if(!b||Object.keys(b).some(k=>!['enabled','events','credentials','allowPrivate'].includes(k))||typeof b.enabled!=='boolean'||!Array.isArray(b.events)||b.events.some((e:any)=>!notificationEvents.includes(e))||new Set(b.events).size!==b.events.length)throw Error('Invalid notification settings');if(b.allowPrivate!==undefined&&(channel!=='email'||typeof b.allowPrivate!=='boolean'))throw Error('Invalid SMTP override');if(b.allowPrivate&&this.sandbox)throw new ControlError('Local/private SMTP is unavailable in sandbox mode.','outbound_refused');let cipher=old?.cipher??null;
 if(b.credentials!==undefined){const c=b.credentials;if(!c||typeof c!=='object'||Array.isArray(c)||Object.values(c).some(v=>typeof v==='string'&&(v.length>4096||/[\r\n]/.test(v))))throw Error('Invalid channel credentials');if(channel==='telegram'){if(Object.keys(c).some(k=>!['token','chatId'].includes(k))||typeof c.token!=='string'||!/^\d{1,20}:[\w-]{10,200}$/.test(c.token)||typeof c.chatId!=='string'||!/^[-\w@]{1,100}$/.test(c.chatId))throw Error('Invalid Telegram channel');}else{if(Object.keys(c).some(k=>!['host','port','secure','user','password','from','to'].includes(k))||typeof c.host!=='string'||! /^[a-zA-Z0-9.:[\]-]{1,253}$/.test(c.host)||![465,587].includes(c.port)||typeof c.secure!=='boolean'||(c.port===465&&!c.secure)||typeof c.user!=='string'||typeof c.password!=='string'||[c.from,c.to].some(v=>typeof v!=='string'||! /^[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}$/.test(v)))throw Error('Invalid SMTP channel; TLS required');}cipher=this.crypt.encrypt(JSON.stringify({...c,...(channel==='email'?{allowPrivate:b.allowPrivate===true}:{})}));}
 else if(channel==='email'&&cipher&&b.allowPrivate!==undefined)cipher=this.crypt.encrypt(JSON.stringify({...JSON.parse(this.crypt.decrypt(cipher)),allowPrivate:b.allowPrivate}));
 if(b.enabled&&!cipher)throw Error('Supply your own channel before enabling');this.db.prepare('INSERT OR REPLACE INTO notification_channels VALUES(?,?,?,?,?)').run(channel,b.enabled?1:0,JSON.stringify(b.events),cipher,'Saved; credentials hidden.');return this.list();}
 remove(channel:string){this.row(channel);this.db.prepare('DELETE FROM notification_channels WHERE channel=?').run(channel);return this.list();}
 async emit(event:string,dedupe?:string,testChannel?:string){if(!eventMessages[event]||(event==='test'&&!testChannel))throw Error('Invalid notification event');const results=[];for(const channel of testChannel?[testChannel]:['telegram','email']){const r=this.row(channel);if(!r?.enabled||!r.cipher||(event!=='test'&&!JSON.parse(r.events).includes(event))){results.push({channel,status:'disabled or event unselected'});continue;}const now=this.clock();if(dedupe&&this.db.prepare('SELECT 1 FROM notification_attempts WHERE channel=? AND dedupe=?').get(channel,dedupe)){results.push({channel,status:'duplicate suppressed'});continue;}if((this.db.prepare('SELECT count(*) AS n FROM notification_attempts WHERE channel=? AND at>?').get(channel,now-60000) as any).n>=5){results.push({channel,status:'rate limited'});continue;}this.db.prepare('INSERT INTO notification_attempts VALUES(?,?,?,?)').run(channel,now,event,dedupe??null);try{const c=JSON.parse(this.crypt.decrypt(r.cipher));if(channel==='email'&&this.sandbox)c.allowPrivate=false;this.guard([eventMessages[event],c.host??'',c.from??'',c.to??'',c.chatId??''].join('\n'));await this.send(channel,c,eventMessages[event]);this.db.prepare('UPDATE notification_channels SET status=? WHERE channel=?').run('Message sent at '+new Date(now).toISOString(),channel);results.push({channel,status:'sent'});}catch(error){const message=error instanceof ControlError?error.message:'Delivery failed. Check your channel settings; retry explicitly.';this.db.prepare('UPDATE notification_channels SET status=? WHERE channel=?').run(message,channel);results.push({channel,status:error instanceof ControlError?message:'delivery failed'});}}return {results};}
 test(channel:string){this.row(channel);return this.emit('test',undefined,channel);}
}
