import type {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
const dayMs=86400000;
export class PortfolioHistory {
 private busy=false;
 constructor(private db:DatabaseSync,private portfolio:()=>Promise<{holdings:any[]}>,private enabled:(id:string)=>boolean,private clock=Date.now){db.exec('CREATE TABLE IF NOT EXISTS portfolio_marks(day TEXT,quote TEXT,value REAL,captured TEXT,sources TEXT,revision TEXT,status TEXT,PRIMARY KEY(day,quote))');}
 async snapshot(){if(this.busy)return;this.busy=true;try{const rows=this.db.prepare('SELECT id,symbol,quantity,cost FROM holdings ORDER BY id').all() as any[],revision=createHash('sha256').update(JSON.stringify(rows)).digest('hex'),now=this.clock(),day=new Date(now).toISOString().slice(0,10),quotes=[...new Set([...rows.map(r=>r.symbol.split('/')[1]),...(this.db.prepare('SELECT DISTINCT quote FROM portfolio_marks').all() as any[]).map(r=>r.quote)])];const pending=quotes.filter(quote=>{const old=this.db.prepare('SELECT revision,status FROM portfolio_marks WHERE day=? AND quote=?').get(day,quote) as any;return !old||old.revision!==revision||old.status!=='observed';});if(!pending.length)return;const p=await this.portfolio();for(const quote of pending){const h=p.holdings.filter(r=>r.symbol.split('/')[1]===quote),sources=[...new Set(h.map(r=>r.exchange).filter(Boolean))],complete=h.every(r=>Number.isFinite(r.value)&&r.source==='public'&&this.enabled(r.exchange));const value=complete?h.reduce((sum,r)=>sum+r.value,0):null;this.db.prepare('INSERT OR REPLACE INTO portfolio_marks VALUES(?,?,?,?,?,?,?)').run(day,quote,value,new Date(now).toISOString(),JSON.stringify(sources),revision,complete?'observed':'gap: price unavailable');}}finally{this.busy=false;}}
 history(days=90){if(!Number.isInteger(days)||days<1||days>3660)throw Error('Invalid history range');const rows=this.db.prepare('SELECT * FROM portfolio_marks ORDER BY day,quote').all() as any[],quotes=[...new Set(rows.map(r=>r.quote))],end=Math.floor(this.clock()/dayMs)*dayMs,start=end-(days-1)*dayMs;return {method:'Daily forward marks, first successful observation per UTC day / holdings revision. Not closing prices or a historical reconstruction. Missed days and revoked sources are gaps. Quote currencies are never summed.',series:quotes.map(quote=>{const byDay=new Map(rows.filter(r=>r.quote===quote).map(r=>[r.day,r]));const points=[];for(let t=start;t<=end;t+=dayMs){const day=new Date(t).toISOString().slice(0,10),r=byDay.get(day),visible=r&&JSON.parse(r.sources).every((id:string)=>this.enabled(id));points.push({day,value:visible?r.value:null,capturedAt:visible?r.captured:null,revision:visible?r.revision:null,sources:visible?JSON.parse(r.sources):[],status:r&&!visible?'gap: source disabled':r?.status??'gap: not observed'});}return {quote,points};})};}
 csv(days=90){const h=this.history(days);return 'day,quote,value,captured_at,sources,holdings_revision,status\n'+h.series.flatMap(s=>s.points.map(p=>[p.day,s.quote,p.value??'',p.capturedAt??'',p.sources.join(';'),p.revision??'',p.status].join(','))).join('\n')+'\n';}
}
