import staticPlugin from '@fastify/static';import {resolve,dirname} from 'node:path';import {randomBytes} from 'node:crypto';import {readFileSync} from 'node:fs';
import {database,service,host,port,version,feedbackSchema,safeComment,screens,type Feedback} from './common.js';import {hashPassword,verifyPassword,digest,vault,newTotpSecret,verifyTotp} from './security.js';import {Market} from './market.js';import {defaults} from './backtest.js';import {versusBTC} from './benchmark.js';import {chat,providers,type Provider} from './ai.js';
const app=service(),data=process.env.DATA_FILE??'/data/app.sqlite',db=database(data),crypt=vault(process.env.MASTER_SECRET_FILE??resolve(dirname(data),'master.secret')),market=new Market(db);
db.exec(`CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT NOT NULL); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,expires INTEGER); CREATE TABLE IF NOT EXISTS providers(id TEXT PRIMARY KEY,model TEXT,base_url TEXT,key_cipher TEXT); CREATE TABLE IF NOT EXISTS holdings(id INTEGER PRIMARY KEY,symbol TEXT,quantity REAL,cost REAL); CREATE TABLE IF NOT EXISTS jobs(id INTEGER PRIMARY KEY,goal TEXT,status TEXT,result TEXT,created TEXT); CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY,job INTEGER,role TEXT,provider TEXT,model TEXT,status TEXT,result TEXT); CREATE TABLE IF NOT EXISTS usage(event TEXT PRIMARY KEY,count INTEGER); CREATE TABLE IF NOT EXISTS tests(id INTEGER PRIMARY KEY,result TEXT,created TEXT)`);
const get=(k:string)=> (db.prepare('SELECT v FROM settings WHERE k=?').get(k) as any)?.v;const set=(k:string,v:string)=>db.prepare('INSERT OR REPLACE INTO settings VALUES(?,?)').run(k,v);
db.exec("UPDATE jobs SET status='interrupted',result='Interrupted by restart. Review and retry explicitly.' WHERE status IN ('queued','running'); UPDATE workers SET status='interrupted',result='Interrupted by restart.' WHERE status IN ('queued','running')");
app.setErrorHandler((err:any,req,reply)=>{reply.code(err.validation?400:400).send({error:err.validation?'Invalid request fields.':'Request failed. Check inputs or provider availability.'});});
const publicAuth=new Set(['/api/auth/state','/api/auth/setup','/api/auth/login']);const attempts=new Map<string,{n:number,until:number}>();
app.addHook('onRequest',async(req,reply)=>{if(['POST','PUT','DELETE'].includes(req.method)){const origin=req.headers.origin;if(origin&&origin!==`${req.protocol}://${req.headers.host}`)return reply.code(403).send({error:'Origin rejected'});if(!req.headers['content-type']?.startsWith('application/json'))return reply.code(415).send({error:'JSON required'});}const path=req.url.split('?')[0];if(path.startsWith('/api/')&&!publicAuth.has(path)){const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8);const row=token&&db.prepare('SELECT expires FROM sessions WHERE token=?').get(digest(token)) as any;if(!row||row.expires<Date.now())return reply.code(401).send({error:'Login required'});}});
const session=(reply:any)=>{const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?)').run(digest(token),Date.now()+8*3600000);reply.header('set-cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.SECURE_COOKIE==='1'?'; Secure':''}`);};
app.get('/health',async()=>({ok:true,version,mode:'paper-only',role:'app'}));app.get('/api/auth/state',async()=>({setup:!get('password'),totp:!!get('totp')}));
app.post('/api/auth/setup',async(req:any,reply)=>{if(get('password'))return reply.code(409).send({error:'Already initialized'});const p=req.body?.password;if(typeof p!=='string'||p.length<12||p.length>200)return reply.code(400).send({error:'Use 12 to 200 characters'});set('password',hashPassword(p));session(reply);return {ok:true};});
app.post('/api/auth/login',async(req:any,reply)=>{const a=attempts.get(req.ip);if(a&&a.until>Date.now()&&a.n>=5)return reply.code(429).send({error:'Wait 15 minutes'});const {password,code}=req.body??{};if(typeof password!=='string'||password.length>200||!get('password')||!verifyPassword(password,get('password'))||(get('totp')&&!verifyTotp(crypt.decrypt(get('totp')),String(code??'')))){attempts.set(req.ip,{n:(a&&a.until>Date.now()?a.n:0)+1,until:Date.now()+900000});return reply.code(401).send({error:'Invalid login'});}attempts.delete(req.ip);session(reply);return {ok:true};});
app.post('/api/auth/logout',async(req,reply)=>{const token=req.headers.cookie?.match(/(?:^|;\s*)session=([^;]+)/)?.[1];if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token));reply.header('set-cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return {ok:true};});
app.post('/api/auth/totp/start',async()=>{const secret=newTotpSecret();set('totp_pending',crypt.encrypt(secret));return {secret,uri:`otpauth://totp/CryptoTools:owner?secret=${secret}&issuer=CryptoTools`};});app.post('/api/auth/totp/confirm',async(req:any,reply)=>{const secret=get('totp_pending');if(!secret||!verifyTotp(crypt.decrypt(secret),String(req.body?.code)))return reply.code(400).send({error:'Invalid code'});set('totp',secret);db.prepare('DELETE FROM settings WHERE k=?').run('totp_pending');return {ok:true};});
app.get('/api/settings',async()=>({telemetry:get('telemetry')==='1',onboarded:get('onboarded')==='1',survey:get('survey')==='1',totp:!!get('totp'),version}));app.post('/api/settings',async(req:any,reply)=>{const b=req.body;if(!b||Object.keys(b).some(k=>!['telemetry','onboarded','survey'].includes(k))||Object.values(b).some(v=>typeof v!=='boolean'))return reply.code(400).send({error:'Invalid settings'});for(const [k,v] of Object.entries(b))set(k,v?'1':'0');return {ok:true};});
const feedbackURL=new URL(process.env.FEEDBACK_URL??'http://feedback:8081/feedback');if(!['http:','https:'].includes(feedbackURL.protocol)||feedbackURL.username||feedbackURL.password)throw Error('Invalid feedback URL');
app.post<{Body:Feedback}>('/api/feedback',{schema:{body:feedbackSchema}},async(req,reply)=>{if(!safeComment(req.body.comment))return reply.code(400).send({error:'Remove sensitive information.'});try{const r=await fetch(feedbackURL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(req.body),signal:AbortSignal.timeout(5000)});return reply.code(r.ok?201:502).send(r.ok?{saved:true}:{error:'Feedback rejected'});}catch{return reply.code(503).send({error:'Feedback unavailable'});}});
app.post('/api/usage',async(req:any,reply)=>{const {event}=req.body??{};if(Object.keys(req.body??{}).length!==1||!([...screens.map(s=>'screen:'+s),'feature:backtest','feature:chat','feature:job'].includes(event)))return reply.code(400).send({error:'Counter events only'});if(get('telemetry')!=='1')return {counted:false};db.prepare('INSERT INTO usage VALUES(?,1) ON CONFLICT(event) DO UPDATE SET count=count+1').run(event);try{await fetch(new URL('/usage',feedbackURL),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event,count:1,version}),signal:AbortSignal.timeout(3000)});}catch{}return {counted:true};});
app.get('/api/tickers',async(req:any)=>({tickers:await Promise.all(['kraken','okx','bybit'].map(async exchange=>{try{return await market.ticker(exchange,req.query.symbol??'BTC/USDT');}catch{return {exchange,status:'unavailable'};}}))}));
function range(b:any){return {exchange:b.exchange??'kraken',symbol:b.symbol??'BTC/USDT',timeframe:b.timeframe??'1d',start:typeof b.start==='number'?b.start:Date.parse(b.start),end:typeof b.end==='number'?b.end:Date.parse(b.end)};}
async function runTest(b:any,persist=false){const r=range(b);if(b.strategy==='trend'&&r.timeframe!=='1d')throw Error('Weekly trend requires daily candles');const {bars,coverage}=await market.ohlcv(r.exchange,r.symbol,r.timeframe,r.start,r.end);const quote=r.symbol.split('/')[1],baselineSymbol=quote==='BTC'?'BTC (native quote)':'BTC/'+quote;const benchmark=quote==='BTC'?{bars:bars.map(x=>[x[0],1,1,1,1,0] as typeof x),coverage}:r.symbol===baselineSymbol?{bars,coverage}:await market.ohlcv(r.exchange,baselineSymbol,r.timeframe,r.start,r.end);const tested=versusBTC(bars,benchmark.bars,{...defaults,...Object.fromEntries(Object.keys(defaults).filter(k=>b[k]!==undefined).map(k=>[k,b[k]]))},quote==='BTC');const actualStart=tested.equity[0].time,actualEnd=tested.equity.at(-1).time+(benchmark.coverage.actualEnd-benchmark.bars.at(-1)![0]);const result={...tested,coverage:{...coverage,actualStart,actualEnd,partial:coverage.partial||benchmark.coverage.partial||tested.equity.length!==bars.length},symbol:r.symbol,timeframe:r.timeframe,baselineSymbol};if(persist)db.prepare('INSERT INTO tests(result,created) VALUES(?,?)').run(JSON.stringify(result),new Date().toISOString());return result;}
app.post('/api/backtest',async(req:any)=>runTest(req.body,true));app.get('/api/backtests/latest',async()=>{const row=db.prepare('SELECT result FROM tests ORDER BY id DESC LIMIT 1').get() as any;return row?JSON.parse(row.result):null;});
async function portfolio(){const rows=db.prepare('SELECT * FROM holdings').all() as any[];return {holdings:await Promise.all(rows.map(async r=>{try{const price=await market.ticker('kraken',r.symbol);return {...r,price:price.last,value:r.quantity*price.last,pnl:r.quantity*(price.last-r.cost),capturedAt:price.capturedAt,status:'live'};}catch{return {...r,value:null,pnl:null,status:'unavailable'};}}))};}
app.get('/api/portfolio',portfolio);app.post('/api/portfolio',async(req:any,reply)=>{const b=req.body;if(Object.keys(b??{}).some(k=>!['symbol','quantity','cost'].includes(k))||! /^[A-Z0-9]{2,15}\/[A-Z0-9]{2,15}$/.test(b?.symbol)||!Number.isFinite(b?.quantity)||b.quantity<=0||b.quantity>1e9||!Number.isFinite(b?.cost)||b.cost<0||b.cost>1e9)return reply.code(400).send({error:'Invalid paper holding'});const r=db.prepare('INSERT INTO holdings(symbol,quantity,cost) VALUES(?,?,?)').run(b.symbol,b.quantity,b.cost);return {id:Number(r.lastInsertRowid)};});app.delete('/api/portfolio/:id',async(req:any)=>{db.prepare('DELETE FROM holdings WHERE id=?').run(Number(req.params.id));return {ok:true};});app.get('/api/portfolio.csv',async(req,reply)=>{const p=await portfolio();reply.type('text/csv').header('content-disposition','attachment; filename="paper-portfolio.csv"');return 'symbol,quantity,cost_per_unit,live_price,value,pnl,status\n'+p.holdings.map(r=>[r.symbol,r.quantity,r.cost,r.price??'',r.value??'',r.pnl??'',r.status].join(',')).join('\n')+'\n';});
app.get('/api/providers',async()=>({available:Object.keys(providers),saved:db.prepare('SELECT id,model,base_url,CASE WHEN key_cipher IS NOT NULL THEN 1 ELSE 0 END AS configured FROM providers').all()}));app.post('/api/providers',async(req:any,reply)=>{const b=req.body;if(!providers[b?.provider]||typeof b.model!=='string'||!b.model||b.model.length>200||typeof b.key!=='string'||b.key.length>4096||typeof b.baseUrl!=='string'||b.baseUrl.length>500||Object.keys(b).some(k=>!['provider','model','key','baseUrl'].includes(k)))return reply.code(400).send({error:'Invalid provider'});const url=new URL(b.baseUrl||providers[b.provider]);if(url.username||url.password||!['http:','https:'].includes(url.protocol)||url.search||url.hash)return reply.code(400).send({error:'Invalid URL'});db.prepare('INSERT OR REPLACE INTO providers VALUES(?,?,?,?)').run(b.provider,b.model,b.baseUrl,crypt.encrypt(b.key));return {saved:true};});
function config(id:string,model?:string):Provider{const row=db.prepare('SELECT * FROM providers WHERE id=?').get(id) as any;if(!row)throw Error('Configure this provider first');return {provider:id,model:model||row.model,baseUrl:row.base_url,key:crypt.decrypt(row.key_cipher)};}
async function tool(name:string,args:any){if(!args||typeof args!=='object'||Array.isArray(args))throw Error('Invalid tool input');if(name==='tickers')return market.ticker(args.exchange??'kraken',args.symbol??'BTC/USDT');if(name==='ohlcv'){const r=range(args);return market.ohlcv(r.exchange,r.symbol,r.timeframe,r.start,r.end);}if(name==='run_backtest')return runTest(args);if(name==='get_portfolio')return portfolio();throw Error('Tool forbidden');}
app.post('/api/chat',async(req:any)=>{const b=req.body;if(typeof b?.prompt!=='string'||!b.prompt.trim()||b.prompt.length>8000)throw Error('Invalid prompt');return chat(config(b.provider,b.model),b.prompt,tool);});
const roles=['research','backtest','risk','reviewer'];let active=false;
async function processJobs(){if(active)return;active=true;try{const jobs=db.prepare("SELECT * FROM jobs WHERE status='queued' ORDER BY id").all() as any[];for(const j of jobs){db.prepare("UPDATE jobs SET status='running' WHERE id=?").run(j.id);let context='';let failed=false;for(const w of db.prepare('SELECT * FROM workers WHERE job=? ORDER BY id').all(j.id) as any[]){db.prepare("UPDATE workers SET status='running' WHERE id=?").run(w.id);try{const r=await chat(config(w.provider,w.model),`Role: ${w.role}. Goal: ${j.goal}. Research and paper-only. ${w.role==='reviewer'?'Challenge prior results and costs; do not rubber-stamp.':''}\nPrior worker outputs:\n${context.slice(-3000)}`,tool);const text=JSON.stringify(r);db.prepare("UPDATE workers SET status='completed',result=? WHERE id=?").run(text,w.id);context+=w.role+': '+r.reply+'\n';}catch{failed=true;db.prepare("UPDATE workers SET status='failed',result='Provider or read-only tool failed. Check settings and retry.' WHERE id=?").run(w.id);}}db.prepare('UPDATE jobs SET status=?,result=? WHERE id=?').run(failed?'failed':'completed',context,j.id);}}finally{active=false;}}
app.post('/api/jobs',async(req:any,reply)=>{const b=req.body;if(typeof b?.goal!=='string'||!b.goal.trim()||b.goal.length>4000||!Array.isArray(b.workers)||b.workers.length!==4)return reply.code(400).send({error:'Goal and four workers required'});for(let i=0;i<4;i++){const w=b.workers[i];if(w.role!==roles[i]||typeof w.model!=='string'||!w.model||w.model.length>200)throw Error('Invalid worker');config(w.provider,w.model);}if(b.workers[3].provider===b.workers[0].provider)return reply.code(400).send({error:'Reviewer must use a different provider'});if(Number((db.prepare("SELECT count(*) AS n FROM jobs WHERE status IN ('running','queued')").get() as any).n)>=3)return reply.code(429).send({error:'Three active jobs maximum'});const r=db.prepare("INSERT INTO jobs(goal,status,result,created) VALUES(?,'queued','',?)").run(b.goal,new Date().toISOString());for(const w of b.workers)db.prepare("INSERT INTO workers(job,role,provider,model,status,result) VALUES(?,?,?,?,'queued','')").run(r.lastInsertRowid,w.role,w.provider,w.model);setTimeout(()=>{void processJobs();},100);return {id:Number(r.lastInsertRowid)};});app.get('/api/jobs',async()=>({jobs:db.prepare('SELECT * FROM jobs ORDER BY id DESC LIMIT 50').all().map((j:any)=>({...j,workers:db.prepare('SELECT * FROM workers WHERE job=? ORDER BY id').all(j.id)}))}));
app.get('/api/news',async()=>({changelog:readFileSync(resolve('CHANGELOG.md'),'utf8')}));
await app.register(staticPlugin,{root:resolve('public')});await app.listen({host,port});for(const signal of ['SIGTERM','SIGINT'] as const)process.on(signal,async()=>{await app.close();db.close();process.exit(0)});
