import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {Staking,normalizeLido,selectOptions,validateFilters,ageSeconds,cacheMs,sourceStaleMs,sortKeys,lidoURL,type Option} from './staking.js';import {definitions} from './ai.js';import {toolProvenance} from './provenance.js';
// RECORDED REAL RESPONSE: Lido public SMA APR, captured 2026-10-07. Synthetic mutations below are expressly test-only.
const recorded=JSON.parse(readFileSync('tests/fixtures/lido-sma-recorded-2026-10-07.json','utf8'));const at=new Date(recorded.capturedAt).toISOString(),raw=recorded.response,initial=Date.parse(at);
const row=()=>normalizeLido(raw,at)[0];
function harness(fetcher?:typeof fetch){const db=new DatabaseSync(':memory:');let now=initial,calls=0;const request:typeof fetch=async(...args)=>{calls++;assert.equal(args[0],lidoURL);return fetcher?fetcher(...args):new Response(JSON.stringify(raw),{headers:{'content-type':'application/json'}})};return {db,make:()=>new Staking(db,request,()=>now,{enabled:id=>id==='lido',require:()=>{},list:()=>[],fetchData:async()=>{const r=await request(lidoURL);if(!r.ok)throw Error('Fixture fetch failed');return r.json();}}),advance:(ms:number)=>{now+=ms},calls:()=>calls};}
test('Lido recorded real response preserves published APR; APY and unsourced fields unknown',()=>{assert.match(recorded.label,/recorded real response/i);assert.equal(recorded.source,lidoURL);const r=row();assert.equal(r.apr,raw.data.smaApr);assert.equal(r.apy,null);assert.equal(r.baseApy,null);assert.equal(r.rewardApy,null);assert.equal(r.lockDays,null);assert.equal(r.lockUp,null);assert.equal(r.minimum,null);assert.equal(r.tvlUsd,null);assert.equal(r.promo,null);assert.equal(r.availability,'unknown');assert.equal(r.sourceTimestamp,new Date(Math.max(...raw.data.aprs.map((r:any)=>r.timeUnix))*1000).toISOString());assert.equal(r.fetchedAt,at);assert.equal(r.type,'liquid staking');assert.equal(r.custody,'user on-chain');assert.deepEqual(r.risks,['slashing','smart contract','depeg']);assert.equal(new URL(r.sourceUrl).search,'');});
test('Malformed Lido rates, metadata and envelope fail closed',()=>{for(const r of [{},{...raw,data:{...raw.data,smaApr:''}},{...raw,data:{...raw.data,smaApr:null}},{...raw,meta:{...raw.meta,chainId:2}},{...raw,meta:{...raw.meta,symbol:'BTC'}},{...raw,data:{...raw.data,aprs:null}}])assert.throws(()=>normalizeLido(r,at));assert.throws(()=>normalizeLido(raw,'invalid'));const r=normalizeLido({...raw,data:{...raw.data,aprs:[]}},at)[0];assert.equal(r.sourceTimestamp,null);assert.equal(selectOptions([r],{},initial)[0].sourceFreshness,'unknown');});
test('Neutral default asset sort and all sortable columns in both directions with unknowns last',()=>{const a={...row(),id:'a',asset:'AAA',apy:3,apr:1,minimum:2,tvlUsd:100,lockDays:3},b={...row(),id:'b',asset:'BBB',apy:2,apr:4,minimum:3,tvlUsd:200,lockDays:2},u={...row(),id:'u',asset:'CCC'};assert.deepEqual(selectOptions([u,b,a],{},initial).map(r=>r.id),['a','b','u']);for(const key of sortKeys)for(const direction of ['asc','desc'] as const){const items=selectOptions([u,b,a],{sort:key,direction},initial);assert.equal(items.length,3);if(['apy','minimum','tvlUsd','lockDays'].includes(key))assert.equal(items.at(-1)!.id,'u');}assert.deepEqual(selectOptions([b,a],{sort:'apr',direction:'desc'},initial).map(r=>r.id),['b','a']);});
test('Filters cover asset type custody max lock TVL and promo with unknowns excluded',()=>{const known={...row(),id:'known',asset:'BTC',type:'exchange earn',custody:'exchange holds coins',lockDays:10,tvlUsd:100,promo:false};const promo={...known,id:'promo',promo:true};const items=[row(),known,promo];assert.equal(selectOptions(items,{asset:'sTeTh'},initial).length,1);assert.equal(selectOptions(items,{type:'exchange earn'},initial).length,2);assert.equal(selectOptions(items,{custody:'user on-chain'},initial).length,1);assert.equal(selectOptions(items,{maxLockDays:9},initial).length,0);assert.equal(selectOptions(items,{maxLockDays:10},initial).length,2);assert.equal(selectOptions(items,{minTvlUsd:100},initial).length,2);assert.equal(selectOptions(items,{minTvlUsd:101},initial).length,0);assert.equal(selectOptions(items,{hidePromo:true},initial).length,1);assert.equal(selectOptions([row()],{minTvlUsd:0},initial).length,0);assert.equal(selectOptions([row()],{maxLockDays:0},initial).length,0);});
test('Strict filters reject unknown controls invalid types non-finite and out of bounds',()=>{for(const f of [null,[],{deposit:true},{sort:'best'},{direction:'wrong'},{maxLockDays:'3'},{maxLockDays:-1},{minTvlUsd:Infinity},{hidePromo:'true'},{type:'unknown'},{custody:'best'},{asset:'x'.repeat(33)}])assert.throws(()=>validateFilters(f));assert.deepEqual(validateFilters({}),{});});
test('Age and stale thresholds stay truthful; fresh retrieval cannot hide old source data',()=>{assert.equal(ageSeconds(null,initial),null);assert.equal(ageSeconds('invalid',initial),null);assert.equal(ageSeconds(at,initial-1000),0);assert.equal(selectOptions([row()],{},initial+cacheMs)[0].freshness,'stale cached snapshot');const r={...row(),sourceTimestamp:new Date(initial-sourceStaleMs-1000).toISOString()};assert.equal(selectOptions([r],{},initial)[0].sourceFreshness,'stale source observation');assert.equal(selectOptions([r],{},initial)[0].freshness,'cached snapshot');});
test('SQLite caches real response source and fetch time across service restart',async()=>{const h=harness();let service=h.make();const a=await service.getOptions();assert.equal(a.options.length,1);assert.equal(h.calls(),1);const stored=h.db.prepare('SELECT * FROM staking_cache').get() as any;assert.equal(stored.source,'lido');assert.equal(stored.fetched_at,at);assert.deepEqual(JSON.parse(stored.payload),raw);h.advance(5000);service=h.make();const b=await service.getOptions();assert.equal(h.calls(),1);assert.equal(b.options[0].fetchedAt,at);assert.equal(b.options[0].fetchedAgeSeconds,5);h.db.close();});
test('Concurrent reads deduplicate upstream request and TTL fetches once when due',async()=>{const h=harness(),s=h.make();await Promise.all(Array.from({length:20},()=>s.getOptions()));assert.equal(h.calls(),1);h.advance(cacheMs);await Promise.all([s.getOptions(),s.getOptions()]);assert.equal(h.calls(),2);h.db.close();});
test('Failure keeps stale data with original fetch time and persisted retry cooldown',async()=>{let failed=false;const h=harness(async()=>{if(failed)throw Error('fixture outage');return new Response(JSON.stringify(raw))}),s=h.make();await s.getOptions();h.advance(cacheMs+1000);failed=true;const b=await s.getOptions();assert.equal(b.options[0].freshness,'stale cached snapshot');assert.equal(b.options[0].fetchedAt,at);assert.match(b.sourceStatus,/failed/);await h.make().getOptions();assert.equal(h.calls(),2);h.db.close();});
test('Empty failed source and invalid payload never create fabricated options',async()=>{for(const fetcher of [async()=>new Response('{}'),async()=>new Response('denied',{status:429})]){const h=harness(fetcher as typeof fetch);const a=await h.make().getOptions();assert.equal(a.total,0);assert.deepEqual(a.options,[]);await h.make().getOptions();assert.equal(h.calls(),1);h.db.close();}});
test('Corrupt SQLite cache is unavailable rather than plausible data',async()=>{const h=harness(),s=h.make();await s.getOptions();h.db.prepare("UPDATE staking_cache SET payload='{}'").run();assert.deepEqual((await s.getOptions()).options,[]);h.db.close();});
test('Read-only AI staking tool returns neutral same data with sources/timestamps and no ranking fields',async()=>{const def=definitions.find(d=>d.name==='get_staking_options')!;assert.ok(def);assert.match(def.description,/neutral|read-only/i);assert.equal(def.parameters.additionalProperties,false);const h=harness(),s=h.make();const data=await s.getOptions({asset:'ETH'});function scan(value:any){for(const [key,val] of Object.entries(value)){assert.ok(!/^(rank|ranking|score|quality|recommendation|recommended|best|affiliate|referral)$/i.test(key),key);if(val&&typeof val==='object')scan(val);}}scan(data);assert.equal(data.options[0].sourceUrl,lidoURL);assert.equal(data.options[0].fetchedAt,at);assert.ok(data.options[0].sourceTimestamp);assert.equal(data.sort.column,'asset');assert.deepEqual(toolProvenance(data),[{source:'public',exchange:'Lido public API',fetchedAt:at}]);h.db.close();});
