import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {chat} from './ai.js';import {Staking} from './staking.js';
const recorded=JSON.parse(readFileSync('tests/fixtures/lido-sma-recorded-2026-10-07.json','utf8'));
for(const native of [false,true])test((native?'Anthropic':'Compatible')+' staking tool roundtrip preserves filters, source timestamps and neutral output',async()=>{
 const db=new DatabaseSync(':memory:'),staking=new Staking(db,async()=>new Response(JSON.stringify(recorded.response)),()=>Date.parse(recorded.capturedAt)),requests:any[]=[];
 const server=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);requests.push(body);res.setHeader('content-type','application/json');const done=body.messages.some((m:any)=>m.role==='tool'||Array.isArray(m.content)&&m.content.some((c:any)=>c.type==='tool_result'));res.end(JSON.stringify(native?{content:done?[{type:'text',text:'Timestamped information only.'}]:[{type:'tool_use',id:'staking',name:'get_staking_options',input:{filters:{asset:'ETH',sort:'asset'}}}]}:{choices:[{message:done?{role:'assistant',content:'Timestamped information only.'}:{role:'assistant',content:null,tool_calls:[{id:'staking',type:'function',function:{name:'get_staking_options',arguments:JSON.stringify({filters:{asset:'ETH',sort:'asset'}})}}]}}]}));});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const result=await chat({provider:native?'anthropic':'openai',model:'fixture',key:'',baseUrl:`http://127.0.0.1:${(server.address() as any).port}/v1`},'Show ETH staking information',async(name,args)=>{assert.equal(name,'get_staking_options');assert.deepEqual(args,{filters:{asset:'ETH',sort:'asset'}});return staking.getOptions(args.filters)});assert.equal(result.reply,'Timestamped information only.');assert.equal(requests.length,2);const delivered=requests[1].messages.find((m:any)=>native?m.role==='user'&&Array.isArray(m.content):m.role==='tool');const data=JSON.parse(native?delivered.content[0].content:delivered.content);assert.equal(data.options[0].source,'Lido public API');assert.equal(data.options[0].fetchedAt,new Date(recorded.capturedAt).toISOString());assert.equal(data.options[0].apy,null);assert.equal(data.options[0].apr,recorded.response.data.smaApr);assert.equal(data.sort.column,'asset');for(const key of ['rank','score','recommendation','recommended','best'])assert.equal(Object.hasOwn(data.options[0],key),false);assert.equal(result.provenance?.source,'public');assert.equal(result.calls[0].name,'get_staking_options');}
 finally{await new Promise<void>(resolve=>server.close(()=>resolve()));db.close();}
});
