import type {DatabaseSync} from 'node:sqlite';
import {publicExchange} from './market.js';
import type {SourceAccess} from './sources.js';
export const spotIds=['kraken','okx','bybit','binance','coinbase'];
import {flowExplanation,washNotice,quoteNotice,trendDefinitions} from './trend-copy.js';
export {flowExplanation,washNotice,quoteNotice,trendDefinitions} from './trend-copy.js';
export type TrendFilters={metric?:keyof typeof trendDefinitions,exchanges?:string[],topN?:number,exchange?:string,symbol?:string,window?:'1h'|'24h'};
export const trendSchema={type:'object',additionalProperties:false,properties:{metric:{type:'string',enum:Object.keys(trendDefinitions)},exchanges:{type:'array',uniqueItems:true,items:{type:'string',enum:spotIds},maxItems:5},topN:{type:'integer',minimum:1,maximum:10},exchange:{type:'string',enum:spotIds},symbol:{type:'string',maxLength:40},window:{type:'string',enum:['1h','24h']}}};
export function validateTrendFilters(input:unknown={}):TrendFilters{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Invalid trend filters');const f=input as any;if(Object.keys(f).some(k=>!Object.keys(trendSchema.properties).includes(k)))throw Error('Unknown trend filter');if(f.metric!==undefined&&!Object.keys(trendDefinitions).includes(f.metric))throw Error('Invalid metric');if(f.exchanges!==undefined&&(!Array.isArray(f.exchanges)||f.exchanges.length>5||new Set(f.exchanges).size!==f.exchanges.length||f.exchanges.some((id:any)=>!spotIds.includes(id))))throw Error('Invalid exchanges');if(f.exchange!==undefined&&!spotIds.includes(f.exchange))throw Error('Invalid exchange');if(f.topN!==undefined&&(!Number.isInteger(f.topN)||f.topN<1||f.topN>10))throw Error('Invalid universe');if(f.symbol!==undefined&&(typeof f.symbol!=='string'||! /^[A-Z0-9.-]{1,20}\/[A-Z0-9.-]{1,15}$/.test(f.symbol)))throw Error('Invalid symbol');if(f.window!==undefined&&!['1h','24h'].includes(f.window))throw Error('Invalid window');return f;}
const finite=(x:any):number|null=>typeof x==='number'&&Number.isFinite(x)?x:null;
const nonnegative=(x:any)=>finite(x)!==null&&x>=0?x:null;
export function usdQuote(q:string){return ['USD','USDT','USDC','DAI','FDUSD','TUSD'].includes(q);}
export function normalizeVolume(exchange:string,market:any,t:any,fetchedAt:string){if(!market?.spot||market.active===false||!usdQuote(market.quote))return null;const quoted=nonnegative(t?.quoteVolume),base=nonnegative(t?.baseVolume),last=finite(t?.last);const volume=quoted??(base!==null&&last!==null&&last>0?base*last:null);if(volume===null||!Number.isFinite(volume))return null;return {exchange,asset:market.base,symbol:market.symbol,quote:market.quote,volumeUsd:volume,approximate:quoted===null,fetchedAt,observedAt:finite(t.timestamp)!==null?new Date(t.timestamp).toISOString():null};}
export function combineVolumes(rows:any[]){const assets=new Map<string,any>();for(const r of rows){let a=assets.get(r.asset);if(!a){a={asset:r.asset,volumeUsd:0,breakdown:[],approximate:false};assets.set(r.asset,a);}a.volumeUsd+=r.volumeUsd;a.approximate||=r.approximate;a.breakdown.push(r);}return [...assets.values()].sort((a,b)=>b.volumeUsd-a.volumeUsd||a.asset.localeCompare(b.asset));}
const day=86400000;
export function surgeMath(volumeUsd:number,bars:any[],now=Date.now()){const end=Math.floor(now/day)*day,start=end-30*day;const good=bars.filter(b=>Array.isArray(b)&&b[0]>=start&&b[0]<end&&b[0]%day===0&&finite(b[4])!==null&&b[4]>0&&nonnegative(b[5])!==null).sort((a,b)=>a[0]-b[0]);const history=good.map(b=>({time:new Date(b[0]).toISOString(),value:b[4]*b[5]}));const complete=good.length===30&&good.every((b,i)=>b[0]===start+i*day);const average=complete?good.reduce((s,b)=>s+b[4]*b[5],0)/30:null;return {ratio:average!==null&&average>0?volumeUsd/average:null,averageDailyUsd:average,days:good.length,complete,history,approximate:true};}
export function aggressorSide(exchange:string,trade:any):'buy'|'sell'|undefined{const raw=trade.info;if(exchange==='kraken'&&Array.isArray(raw)&&['b','s'].includes(raw[3]))return raw[3]==='b'?'buy':'sell';if(exchange==='okx'&&['buy','sell'].includes(raw?.side))return raw.side;if(exchange==='bybit'&&['Buy','Sell'].includes(raw?.side))return raw.side==='Buy'?'buy':'sell';if(exchange==='binance'){const maker=typeof raw?.m==='boolean'?raw.m:raw?.isBuyerMaker;if(typeof maker==='boolean')return maker?'sell':'buy';}if(exchange==='coinbase'&&['buy','sell'].includes(raw?.side))return raw.side==='buy'?'sell':'buy';return undefined;}
export function flowMath(trades:any[],window:'1h'|'24h',now=Date.now()){const hours=window==='1h'?1:24,start=now-hours*3600000;const timestamps=trades.map(t=>finite(t.timestamp)).filter((t):t is number=>t!==null&&t<=now);const oldest=timestamps.length?Math.min(...timestamps):null,newest=timestamps.length?Math.max(...timestamps):null;const complete=oldest!==null&&oldest<=start&&newest!==null&&newest>=now-60000;let acquisitionUsd=0,disposalUsd=0,unknownCount=0,observedCount=0;const buckets=Array.from({length:12},(_,i)=>({time:new Date(start+i*hours*3600000/12).toISOString(),acquisitionUsd:0,disposalUsd:0}));const seen=new Set<string>();for(const t of trades){const ts=finite(t.timestamp);if(ts===null||ts<start||ts>now)continue;const key=t.id!==undefined?String(t.id):null;if(key!==null&&seen.has(key))continue;if(key!==null)seen.add(key);const value=nonnegative(t.cost)??(finite(t.price)!==null&&nonnegative(t.amount)!==null?t.price*t.amount:null);if(value===null||!Number.isFinite(value)||!['buy','sell'].includes(t.side)){unknownCount++;continue;}observedCount++;const b=buckets[Math.min(11,Math.floor((ts-start)/(hours*3600000/12)))];if(t.side==='buy'){acquisitionUsd+=value;b.acquisitionUsd+=value;}else{disposalUsd+=value;b.disposalUsd+=value;}}const total=acquisitionUsd+disposalUsd;return {window,complete,windowAcquisitionUsd:complete&&unknownCount===0?acquisitionUsd:null,windowDisposalUsd:complete&&unknownCount===0?disposalUsd:null,sample:{acquisitionUsd,disposalUsd,acquisitionShare:total>0?acquisitionUsd/total:null,observedCount,unknownCount,oldest:oldest===null?null:new Date(oldest).toISOString(),newest:newest===null?null:new Date(newest).toISOString()},history:buckets,explanation:flowExplanation};}
export function listingDiff(previous:string[]|null,current:string[],time:string){const old=new Set(previous??[]);return {baseline:previous===null,added:previous===null?[]:[...new Set(current)].filter(s=>!old.has(s)).sort().map(symbol=>({symbol,firstSeen:time}))};}
export const bannedWords=/\b(?:bullish|bearish|buy|sell|recommend(?:s|ed|ing|ation|ations)?)\b/i;
export function neutralOutput(value:any){const text=JSON.stringify(value).split(flowExplanation).join('');if(bannedWords.test(text))throw Error('Non-neutral output refused');return value;}
type Access=Pick<SourceAccess,'enabled'|'require'|'list'>&{status?:(id:string,text:string,fetched?:boolean)=>void};
export class Trends{
 private exchanges=new Map<string,any>();private inflight=new Map<string,Promise<any>>();
 constructor(private db:DatabaseSync,private access:Access,private factory=publicExchange,private clock=Date.now){db.exec('CREATE TABLE IF NOT EXISTS trend_cache(k TEXT PRIMARY KEY,payload TEXT NOT NULL,fetched_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS trend_snapshots(exchange TEXT PRIMARY KEY,payload TEXT NOT NULL,taken_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS trend_listings(exchange TEXT,symbol TEXT,first_seen TEXT,PRIMARY KEY(exchange,symbol))');}
 private ex(id:string,derivatives=false){this.access.require(id);const key=id+':'+derivatives;if(!this.exchanges.has(key))this.exchanges.set(key,this.factory(id,()=>this.access.require(id),derivatives));return this.exchanges.get(key);}
 private async cached(id:string,key:string,ttl:number,fetcher:()=>Promise<any>){this.access.require(id);const k=id+':'+key,row=this.db.prepare('SELECT * FROM trend_cache WHERE k=?').get(k) as any;if(row&&this.clock()-Date.parse(row.fetched_at)<ttl){this.access.require(id);return {...JSON.parse(row.payload),fetchedAt:row.fetched_at};}if(this.inflight.has(k))return this.inflight.get(k);const promise=(async()=>{const payload=await fetcher();this.access.require(id);const fetchedAt=new Date(this.clock()).toISOString();this.db.prepare('INSERT OR REPLACE INTO trend_cache VALUES(?,?,?)').run(k,JSON.stringify(payload),fetchedAt);this.access.status?.(id,'Public trend snapshot fetched.',true);return {...payload,fetchedAt};})();this.inflight.set(k,promise);try{return await promise}finally{this.inflight.delete(k)}}
 private async volumes(id:string){return this.cached(id,'volumes',300000,async()=>{const ex=this.ex(id),markets=await ex.loadMarkets();this.access.require(id);const spot=Object.values(markets).filter((m:any)=>m.spot&&m.active!==false) as any[];if(!ex.has.fetchTickers)throw Error('Ticker universe unavailable');const tickers=await ex.fetchTickers();const time=new Date(this.clock()).toISOString(),rows:any[]=[];let excludedQuote=0,excludedData=0;for(const m of spot){if(!usdQuote(m.quote)){excludedQuote++;continue;}const row=normalizeVolume(id,m,tickers[m.symbol],time);if(row)rows.push(row);else excludedData++;}const previous=this.db.prepare('SELECT payload FROM trend_cache WHERE k=?').get(id+':volumes') as any;const oldRows=previous?JSON.parse(previous.payload).rows:[];for(const r of rows){const history=oldRows.find((o:any)=>o.symbol===r.symbol)?.history??[];r.history=[...history,{time,value:r.volumeUsd}].slice(-60);}return {status:rows.length?'available':'unknown: public batch tickers omit usable turnover',rows,excludedQuote,excludedData,marketCount:spot.length};});}
 private async surges(id:string,n:number){const volume=await this.volumes(id);const rows=[...volume.rows].sort((a,b)=>b.volumeUsd-a.volumeUsd||a.symbol.localeCompare(b.symbol)).slice(0,n);const results=[];for(const r of rows){try{const h=await this.cached(id,'daily:'+r.symbol+':'+Math.floor(this.clock()/day),3600000,async()=>{const ex=this.ex(id);if(!ex.has.fetchOHLCV)throw Error('History unavailable');const bars=await ex.fetchOHLCV(r.symbol,'1d',Math.floor(this.clock()/day)*day-30*day,31);return {bars};});results.push({...r,...surgeMath(r.volumeUsd,h.bars,this.clock()),historyFetchedAt:h.fetchedAt});}catch{this.access.require(id);results.push({...r,ratio:null,averageDailyUsd:null,days:0,complete:false,history:[],historyFetchedAt:null,historyStatus:'unknown'});}}return {...volume,rows:results,universeN:n};}
 private async listings(id:string){return this.cached(id,'listings',900000,async()=>{const markets=await this.ex(id).loadMarkets(true);this.access.require(id);const current=(Object.values(markets) as any[]).filter(m=>m.spot&&m.active!==false).map(m=>m.symbol).sort();const row=this.db.prepare('SELECT * FROM trend_snapshots WHERE exchange=?').get(id) as any;const time=new Date(this.clock()).toISOString(),diff=listingDiff(row?JSON.parse(row.payload):null,current,time);for(const a of diff.added)this.db.prepare('INSERT OR IGNORE INTO trend_listings VALUES(?,?,?)').run(id,a.symbol,a.firstSeen);this.db.prepare('INSERT OR REPLACE INTO trend_snapshots VALUES(?,?,?)').run(id,JSON.stringify(current),time);return {...diff,previousSnapshotAt:row?.taken_at??null,marketCount:current.length,added:diff.added.map(a=>({...a,firstSeen:(this.db.prepare('SELECT first_seen FROM trend_listings WHERE exchange=? AND symbol=?').get(id,a.symbol) as any).first_seen})),history:(this.db.prepare('SELECT symbol,first_seen AS firstSeen FROM trend_listings WHERE exchange=? ORDER BY first_seen DESC,symbol LIMIT 50').all(id))};});}
 private async flow(id:string,symbol:string,window:'1h'|'24h'){return this.cached(id,'flow:'+symbol+':'+window,60000,async()=>{const ex=this.ex(id);const markets=await ex.loadMarkets(),m=markets[symbol];if(!m?.spot||m.active===false||!usdQuote(m.quote)||!ex.has.fetchTrades)throw Error('Flow unavailable');const since=this.clock()-(window==='1h'?3600000:86400000);const limit=id==='bybit'?60:id==='okx'?100:1000;const trades=await ex.fetchTrades(symbol,since-60000,limit);return {symbol,quote:m.quote,limit,...flowMath(trades.map((t:any)=>({...t,side:aggressorSide(id,t)})),window,this.clock()),semantics:'Initiating side requires the explicit provider side/maker field, including Coinbase maker-side inversion; absent fields stay unknown. No private trades are requested.'};});}
 private async futures(id:string,symbol:string){return this.cached(id,'futures:'+symbol,300000,async()=>{const asset=symbol.split('/')[0];if(!['okx','bybit','binance'].includes(id))return {symbol,contract:null,fundingRate:null,fundingTimestamp:null,nextFundingAt:null,openInterestAmount:null,openInterestValue:null,interestTimestamp:null,basisPct:null,spotPrice:null,perpPrice:null,history:[],status:'unknown: connector does not expose keyless perpetual metrics'};const ex=this.ex(id,true),markets=await ex.loadMarkets();const candidates=(Object.values(markets) as any[]).filter(m=>m.swap&&m.linear&&m.active!==false&&m.base===asset&&m.quote===symbol.split('/')[1]);const m=candidates.sort((a,b)=>a.symbol.localeCompare(b.symbol))[0];if(!m)return {symbol,contract:null,status:'unknown: matching linear perpetual unavailable',fundingRate:null,openInterestAmount:null,openInterestValue:null,basisPct:null,history:[]};let funding:any=null,oi:any=null,spot:any=null,perp:any=null;try{if(ex.has.fetchFundingRate)funding=await ex.fetchFundingRate(m.symbol)}catch{}try{if(ex.has.fetchOpenInterest)oi=await ex.fetchOpenInterest(m.symbol)}catch{}try{spot=await this.ex(id).fetchTicker(symbol);perp=await ex.fetchTicker(m.symbol)}catch{}this.access.require(id);const s=finite(spot?.last),p=finite(perp?.last),time=new Date(this.clock()).toISOString(),rate=finite(funding?.fundingRate);const previous=this.db.prepare('SELECT payload FROM trend_cache WHERE k=?').get(id+':futures:'+symbol) as any;const history=previous?(JSON.parse(previous.payload).history??[]):[];if(rate!==null)history.push({time,value:rate});return {symbol,contract:m.symbol,fundingRate:rate,fundingTimestamp:finite(funding?.timestamp)!==null?new Date(funding.timestamp).toISOString():null,nextFundingAt:finite(funding?.nextFundingTimestamp)!==null?new Date(funding.nextFundingTimestamp).toISOString():null,openInterestAmount:nonnegative(oi?.openInterestAmount),openInterestValue:nonnegative(oi?.openInterestValue),interestTimestamp:finite(oi?.timestamp)!==null?new Date(oi.timestamp).toISOString():null,basisPct:s!==null&&s>0&&p!==null?(p/s-1)*100:null,spotPrice:s,perpPrice:p,priceObservedAt:finite(perp?.timestamp)!==null?new Date(perp.timestamp).toISOString():null,history:history.slice(-60),status:'public snapshot; unavailable fields unknown'};});}
 async get(input:unknown={}){const f=validateTrendFilters(input),metric=f.metric??'leaders',enabled=spotIds.filter(id=>this.access.enabled(id)),ids=(f.exchanges??enabled).filter(id=>enabled.includes(id));const selected=f.exchange??ids[0];const requested=['flow','futures'].includes(metric)?(selected&&ids.includes(selected)?[selected]:[]):ids;const sources:any[]=[];for(const id of requested){try{const data=metric==='leaders'?await this.volumes(id):metric==='surges'?await this.surges(id,f.topN??3):metric==='listings'?await this.listings(id):metric==='flow'?await this.flow(id,f.symbol??(id==='coinbase'?'BTC/USD':'BTC/USDT'),f.window??'1h'):await this.futures(id,f.symbol??(id==='coinbase'?'BTC/USD':'BTC/USDT'));this.access.require(id);sources.push({exchange:id,source:'ccxt '+id+' public API',sourceUrl:this.access.list().find(s=>s.id===id)?.docs??null,status:'available',ageSeconds:Math.max(0,Math.floor((this.clock()-Date.parse(data.fetchedAt))/1000)),...data});}catch{if(this.access.enabled(id))sources.push({exchange:id,source:'ccxt '+id+' public API',sourceUrl:this.access.list().find(s=>s.id===id)?.docs??null,status:'unknown: provider or metric unavailable',fetchedAt:null,ageSeconds:null,rows:[]});}}
 // A source may be disabled during a multi-exchange request. Filter again before exposing caches.
 const visible=sources.filter(s=>this.access.enabled(s.exchange)),rows=visible.flatMap(s=>s.rows??[]);const combined=metric==='leaders'?combineVolumes(rows):[];return neutralOutput({metric,definition:trendDefinitions[metric],asOf:new Date(this.clock()).toISOString(),enabledExchanges:enabled.filter(id=>this.access.enabled(id)),sources:visible,combined,displayLimit:20,universeN:metric==='surges'?f.topN??3:null,washNotice:['leaders','surges','flow'].includes(metric)?washNotice:null,quoteNotice:['leaders','surges','flow'].includes(metric)?quoteNotice:null,scope:'Observed public snapshots, not forecasts. Past behaviour is not a promise. Sources are selected by you; availability and access rights remain your responsibility.'});}
}
