import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:http';
import {vault} from './security.js';import {SecretGuard} from './secret-guard.js';import {safeComment} from './common.js';import {Sessions,idleTimeoutMs,absoluteLifetimeMs} from './sessions.js';import {publicAddress,resolveOutbound,requestJSON,aiPolicy,feedbackPolicy,defaultFeedbackURL} from './outbound.js';import {Notifications} from './notifications.js';
test('review canaries: all held secrets and master encodings block before outbound; plaintext is never cached',()=>{
 const d=new DatabaseSync(':memory:'),dir=mkdtempSync(join(tmpdir(),'v074-guard-')),old=process.env.MASTER_SECRET;process.env.MASTER_SECRET='CTREVIEW-MASTER-synthetic-notlive-'.repeat(2);
 try{const crypt=vault(join(dir,'master.secret'));d.exec('CREATE TABLE providers(key_cipher TEXT); CREATE TABLE data_sources(key_cipher TEXT); CREATE TABLE notification_channels(cipher TEXT); CREATE TABLE settings(k TEXT,v TEXT)');const values:string[]=[];
 for(const id of ['openai','anthropic','mistral','gemini','deepseek','openrouter','zen','ollama']){const value='CTREVIEW-'+id+'-synthetic-notlive';values.push(value);d.prepare('INSERT INTO providers VALUES(?)').run(crypt.encrypt(value));}
 for(const [table,value] of [['data_sources',{key:'CTREVIEW-LLAMA-synthetic-notlive'}],['data_sources',{key:'CTREVIEW-SOURCE-synthetic-notlive',secret:'CTREVIEW-SECRET-synthetic-notlive',passphrase:'CTREVIEW-PASSPHRASE-synthetic-notlive'}],['notification_channels',{token:'6012345678:CTREVIEW-TGTOKEN-synthetic-0123456789',chatId:'12345'}],['notification_channels',{password:'CTREVIEW-SMTPPASS-synthetic-notlive',host:'mail.example'}]] as const){d.prepare(`INSERT INTO ${table} VALUES(?)`).run(crypt.encrypt(JSON.stringify(value)));values.push(...Object.entries(value).filter(([k])=>['key','secret','passphrase','token','password'].includes(k)).map(([,v])=>v));}
 for(const k of ['totp','totp_pending']){const value='CTREVIEW-'+k+'-synthetic';values.push(value);d.prepare('INSERT INTO settings VALUES(?,?)').run(k,crypt.encrypt(value));}
 const g=new SecretGuard(d,crypt);for(const value of values)assert.throws(()=>g.assert('Here is '+value),/Nothing was sent/);
 for(const encoding of ['utf8','hex','base64','base64url'] as const)assert.equal(g.contains(Buffer.from(process.env.MASTER_SECRET).toString(encoding)),true);
 const escaped='CTREVIEW-quoted"passphrase\\with\nnewline';d.prepare('INSERT INTO data_sources VALUES(?)').run(crypt.encrypt(JSON.stringify({passphrase:escaped})));assert.throws(()=>g.assertValue({messages:[{content:JSON.stringify({nested:escaped})}]}),/Nothing was sent/);assert.throws(()=>g.assertValue({model:values[0]}),/Nothing was sent/);
 g.assert('The settings screen is easy to find.');assert.equal(g.contains('mail.example'),false);assert.equal(g.contains('12345'),false);
 }finally{d.close();rmSync(dir,{recursive:true,force:true});if(old===undefined)delete process.env.MASTER_SECRET;else process.env.MASTER_SECRET=old;}
});
test('hashed auth material and raw session nonce are blocked without plaintext session storage',()=>{const d=new DatabaseSync(':memory:');d.exec('CREATE TABLE settings(k TEXT,v TEXT)');const crypt={decrypt:(s:string)=>s,containsSecret:()=>false},g=new SecretGuard(d,crypt),sessions=new Sessions(d),token=sessions.issue(),stored=(d.prepare('SELECT token FROM sessions').get() as any).token;try{assert.notEqual(stored,token);assert.equal(g.contains('Cookie: session='+token),true);assert.equal(g.contains('Cookie: session='+token.toUpperCase()),true);assert.equal(g.contains(stored),true);const hash='CTREVIEW-SCRYPT-HASH-synthetic-notlive';d.prepare('INSERT INTO settings VALUES(?,?)').run('password',hash);assert.equal(g.contains(hash),true);sessions.revoke(token);assert.equal(g.contains(token),false);}finally{d.close();}});
test('pattern fallback: Gemini, Mistral, Anthropic, Telegram, JWT and PEM',()=>{for(const value of ['AIza'+'x'.repeat(35),'a'.repeat(32),'sk-ant-'+'x'.repeat(25),'sk-'+'x'.repeat(20),'6012345678:'+'x'.repeat(35),'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.syntheticSignature','-----BEGIN RSA PRIVATE KEY-----','-----BEGIN OPENSSH PRIVATE KEY-----','api_key: synthetic','password=synthetic'])assert.equal(safeComment(value),false,value.slice(0,8));assert.equal(safeComment('The settings form needs clearer labels.'),true);});
test('non-public IPv4/IPv6, CGNAT, metadata and mapped addresses denied by default',async()=>{
 for(const ip of ['0.0.0.0','10.1.2.3','100.64.0.1','100.127.255.255','127.0.0.1','169.254.169.254','172.16.1.1','172.31.255.255','192.168.1.1','224.0.0.1','255.255.255.255','::','::1','fc00::1','fd12::1','fe80::1','ff02::1','::ffff:127.0.0.1','::ffff:192.168.1.1','2001:db8::1','2002:7f00:1::']){assert.equal(publicAddress(ip),false,ip);await assert.rejects(()=>resolveOutbound(ip),/refused/);}
 for(const ip of ['8.8.8.8','100.63.255.255','172.32.0.1','2606:4700:4700::1111'])assert.equal(publicAddress(ip),true,ip);
 await assert.rejects(()=>resolveOutbound('mixed.example',{},async()=>[{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}]),/refused/);
 assert.equal((await resolveOutbound('127.0.0.1',{allowPrivate:true})).address,'127.0.0.1');
});
test('connect-time re-resolution detects DNS rebinding; Ollama exception is loopback-only and sandbox disabled',async()=>{
 let n=0;const dns=async()=>[{address:++n===1?'8.8.8.8':'169.254.169.254',family:4}];assert.equal((await resolveOutbound('relay.example',{},dns)).address,'8.8.8.8');await assert.rejects(()=>resolveOutbound('relay.example',{},dns),/refused/);
 assert.throws(()=>aiPolicy('openai',true,false),/unavailable/);assert.throws(()=>aiPolicy('ollama',true,true),/unavailable/);await assert.rejects(()=>resolveOutbound('10.0.0.1',aiPolicy('ollama',true,false)),/refused/);
 const s=createServer((req,res)=>res.end(JSON.stringify({ok:true})));await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(s.address() as any).port+'/v1';try{await assert.rejects(()=>requestJSON(url,{},{}),/refused/);assert.deepEqual(await (await requestJSON(url,{}, {},aiPolicy('ollama',true,false))).json(),{ok:true});}finally{await new Promise<void>(r=>s.close(()=>r()));}
});
test('only the fixed feedback companion is exempt; custom feedback and telemetry URLs use public address policy',async()=>{assert.deepEqual(feedbackPolicy(new URL(defaultFeedbackURL)),{allowPrivate:true});for(const url of ['http://127.0.0.1:8081/feedback','https://10.0.0.1/feedback','https://169.254.169.254/feedback','http://feedback:9999/feedback','http://feedback:8081/other']){const u=new URL(url);assert.deepEqual(feedbackPolicy(u),{});if(u.hostname!=='feedback')await assert.rejects(()=>requestJSON(url,{},{} ,feedbackPolicy(u)),/refused/);}const local=createServer((req,res)=>res.end('{"ok":true}'));await new Promise<void>(r=>local.listen(0,'127.0.0.1',r));try{assert.deepEqual(await (await requestJSON('http://127.0.0.1:'+(local.address() as any).port+'/feedback',{}, {},{allowPrivate:true})).json(),{ok:true});}finally{await new Promise<void>(r=>local.close(()=>r()));}});
test('SMTP private toggle default off, explicit warning metadata, sandbox refusal and retained override updates',()=>{const d=new DatabaseSync(':memory:'),crypt={encrypt:(s:string)=>s,decrypt:(s:string)=>s},credentials={host:'::1',port:465,secure:true,user:'fixture',password:'synthetic',from:'a@example.org',to:'b@example.org'};try{const n=new Notifications(d,crypt,false);n.update('email',{enabled:true,events:[],credentials});assert.equal(n.list().channels.find(c=>c.channel==='email')!.allowPrivate,false);n.update('email',{enabled:true,events:[],allowPrivate:true});assert.equal(n.list().channels.find(c=>c.channel==='email')!.allowPrivate,true);const sandbox=new Notifications(d,crypt,true);assert.throws(()=>sandbox.update('email',{enabled:true,events:[],allowPrivate:true}),/sandbox/);n.update('email',{enabled:true,events:[],allowPrivate:false});assert.equal(n.list().channels.find(c=>c.channel==='email')!.allowPrivate,false);}finally{d.close();}});
test('sessions migrate fail closed, survive restart, expire at idle/absolute bounds and revoke server-side',()=>{const d=new DatabaseSync(':memory:');let now=1000000;d.exec("CREATE TABLE sessions(token TEXT PRIMARY KEY,expires INTEGER); INSERT INTO sessions VALUES('old',999999999)");const s=new Sessions(d,()=>now);assert.equal((d.prepare('SELECT count(*) AS n FROM sessions').get() as any).n,0);const token=s.issue();assert.ok(new Sessions(d,()=>now).valid(token));now+=idleTimeoutMs-1;assert.ok(s.valid(token));now+=idleTimeoutMs;assert.equal(s.valid(token),false);const active=s.issue();for(let t=0;t<absoluteLifetimeMs-idleTimeoutMs;t+=idleTimeoutMs-1){now+=idleTimeoutMs-1;if(now<1000000+2*idleTimeoutMs-1+absoluteLifetimeMs)assert.ok(s.valid(active));}now=1000000+2*idleTimeoutMs-1+absoluteLifetimeMs;assert.equal(s.valid(active),false);const a=s.issue(),b=s.issue();s.revoke(a);assert.equal(s.valid(a),false);assert.ok(s.valid(b));s.revokeAll();assert.equal(s.valid(b),false);d.close();});
