import React,{useEffect,useState} from 'react';
async function request(path:string,data?:any,method='POST'){const r=await fetch('/api/sources'+path,data===undefined?{}:{method,headers:{'content-type':'application/json'},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error??'Source settings failed');return b;}
export function DataSourcesScreen({compact=false,onChange}:{compact?:boolean,onChange?:()=>void}){
 const [data,D]=useState<any>(null),[error,E]=useState('');const load=()=>request('').then(D).catch(e=>E(e.message));useEffect(()=>{void load()},[]);
 return <section aria-label="Data source settings" className={compact?'source-onboarding':''}><p>Your data, your access. Nothing is enabled by default. This app supplies connectors, not data or access rights. Choose only sources you may use under their terms.</p><p className="muted">Acceptance here does not grant a licence or override restrictions on commercial use or redistribution.</p>{data?.sandbox&&<article role="note"><b>Hosted tester sandbox</b><p>Install locally to use your own exchange keys or a paid data key. Only keyless sources can be enabled here.</p></article>}{data?.migrationNotice&&<article role="note"><b>Existing sources were disabled for this update.</b><p>Review each provider’s terms and accept them before enabling its connector.</p><button onClick={async()=>{await request('/notice',{});await load()}}>Dismiss update notice</button></article>}<p className="error" role="alert">{error}</p><div className="source-grid">{data?.sources.map((source:any)=><SourceCard key={source.id} source={source} changed={async()=>{await load();onChange?.()}}/>)}</div></section>;
}
function SourceCard({source:s,changed}:any){const [accepted,A]=useState(s.accepted),[enabled,N]=useState(s.enabled),[status,T]=useState(''),[busy,B]=useState(false);useEffect(()=>{N(s.enabled);A(s.accepted)},[s.enabled,s.accepted]);
 const run=async(fn:()=>Promise<any>)=>{B(true);T('');try{await fn();await changed()}catch(e:any){T(e.message);await changed()}finally{B(false)}};
 return <article className="source-card" data-source={s.id}><div className="section-title"><h2>{s.name}</h2><span className="badge">{s.enabled?'Enabled':'Off'}</span></div><p>{s.provides}</p><p>{s.key?'Your own key required.':'No key needed.'}</p><div className="actions"><a href={s.terms} target="_blank" rel="noopener noreferrer">Provider terms</a><a href={s.docs} target="_blank" rel="noopener noreferrer">API docs</a></div>{s.key&&s.exchange&&<p className="source-warning">Create a READ-ONLY key: no trading, transfers or withdrawals. Use IP whitelisting on a VPS. {s.permissionWarning??'Permission checks run before enabling and on each fetch; unsafe or unverified keys are refused.'}</p>}{s.sandboxBlocked&&<p>Install locally to use your own exchange keys or paid data access.</p>}
 <form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;void run(async()=>{const f=new FormData(form),credentials:any={key:f.get('key')?.toString()??'',secret:f.get('secret')?.toString()??'',passphrase:f.get('passphrase')?.toString()??''};await request('/'+s.id,{accepted,enabled,...(credentials.key?{credentials}:{})});form.reset();T('Saved. Credentials are hidden.');})}}>
 <label className="check"><input type="checkbox" checked={accepted} onChange={e=>{A(e.target.checked);if(!e.target.checked)N(false)}} disabled={s.sandboxBlocked||busy}/>I have read and accept this provider’s terms; I use this source under my own account</label>
 {s.key&&<><label>API key<input name="key" type="password" autoComplete="new-password" disabled={s.sandboxBlocked||busy} placeholder={s.configured?'Saved key hidden; leave blank to keep':'Your own provider key'}/></label>{s.exchange&&<label>API secret<input name="secret" type="password" autoComplete="new-password" disabled={s.sandboxBlocked||busy}/></label>}{s.id==='okx-earn'&&<label>API passphrase<input name="passphrase" type="password" autoComplete="new-password" disabled={s.sandboxBlocked||busy}/></label>}</>}
 <label className="check"><input aria-label={'Enable '+s.name} type="checkbox" checked={enabled} onChange={e=>N(e.target.checked)} disabled={!accepted||s.sandboxBlocked||busy}/>Enable this source</label><button className="primary" disabled={busy||s.sandboxBlocked}>Save source</button><button type="button" disabled={!s.enabled||busy} onClick={()=>run(async()=>{const r=await request('/'+s.id+'/test',{});T(r.status)})}>Test connection</button>{s.key&&<button type="button" disabled={busy||!s.configured} onClick={()=>run(async()=>{await request('/'+s.id+'/key',{},'DELETE');formClear();T('Key deleted; source disabled.')})}>Delete key</button>}</form>
 <p role="status">{status}</p><small>Last status: {s.lastStatus}<br/>Last fetch: {s.lastFetch??'never'}</small></article>;
 function formClear(){const node=document.querySelector(`[data-source="${s.id}"] form`) as HTMLFormElement|null;node?.reset();}
}
export function SourceEmpty({open}:{open?:()=>void}){return <article className="empty source-empty"><h3>Choose your data sources</h3><p>No market source is enabled. Nothing is fetched until you accept a provider’s terms and enable its connector.</p><button onClick={open??(()=>window.dispatchEvent(new Event('open-data-sources')))}>Open Data sources</button></article>}
