import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
function App(){const [screen,setScreen]=useState('market'),[tickers,setTickers]=useState<any[]>([]),[error,setError]=useState(''),[modal,setModal]=useState(false),[comment,setComment]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
async function refresh(){setError('');try{const r=await fetch('/api/tickers');if(!r.ok)throw Error();setTickers((await r.json()).tickers)}catch{setError('Market data unavailable. Please retry.')}}
useEffect(()=>{refresh()},[]);
async function send(e:React.FormEvent){e.preventDefault();if(/(?:-----BEGIN|sk-[A-Za-z0-9_-]{10,}|(?:api[_ -]?key|secret|password|balance)\s*[:=])/i.test(comment)){setStatus('Remove sensitive information before sending.');return}setBusy(true);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({comment,version:'0.1.0',screen})});if(!r.ok)throw Error();setStatus('Feedback saved. Thank you.');setComment('')}catch{setStatus('Could not send. Your comment is still here; please retry.')}finally{setBusy(false)}}
return <><header><strong>cryptotools <small>0.1.0</small></strong><nav>{['market','about'].map(s=><button key={s} aria-current={screen===s?'page':undefined} onClick={()=>setScreen(s)}>{s==='market'?'Market':'About'}</button>)}</nav></header><main><div className="banner">Public-data prototype · Paper-only beta · No trading or credentials</div>{screen==='market'?<><p className="eyebrow">LIVE PUBLIC SPOT DATA</p><h1>One market. Two views.</h1><p>BTC / USDT from Kraken and OKX. Prices can differ by venue.</p><div className="grid">{tickers.length?tickers.map(t=><article key={t.exchange}><h2>{t.exchange.toUpperCase()}</h2><small>{t.symbol} · {t.status}</small><h3>{t.status==='live'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(t.last):'Unavailable'}</h3><p>Quote unit: USDT{t.capturedAt&&<> · captured {new Date(t.capturedAt).toLocaleTimeString()}</>}</p></article>):<p>Loading public exchange data…</p>}</div><p role="alert">{error}</p><button onClick={refresh}>Refresh prices</button></>:<><h1>A deployment-first prototype.</h1><p>The API runs without this browser. Market observations live in a local SQLite volume.</p><p>Feedback is a separate service. It receives only your comment, this screen name and the app version.</p><p>Portfolio, test bench, AI and order execution are not implemented. No exchange keys are collected.</p></>}</main><footer><span>Local workspace · Public endpoints only</span><button className="primary" onClick={()=>{setModal(true);setStatus('')}}>Send feedback</button></footer>{modal&&<div className="overlay"><section role="dialog" aria-modal="true" aria-labelledby="feedback-title"><h2 id="feedback-title">Help shape the beta</h2><p>Do not include keys, balances, trades, chat text or personal information.</p><form onSubmit={send}><label htmlFor="comment">Comment</label><textarea id="comment" required maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/><p>Sending: comment + version 0.1.0 + screen {screen}</p><p role="status">{status}</p><button type="submit" disabled={busy} className="primary">{busy?'Sending…':'Send comment'}</button> <button type="button" onClick={()=>setModal(false)}>Close</button></form></section></div>}</>}
createRoot(document.getElementById('root')!).render(<App/>);
