import React,{useEffect,useState} from 'react';import {SourceEmpty} from './DataSources.js';
const columns=[['asset','Asset'],['venue','Venue / protocol'],['type','Type'],['apy','APY'],['apr','APR'],['rateType','Rate type'],['lockDays','Lock / unbonding'],['custody','Custody'],['risks','Listed risks'],['minimum','Minimum amount'],['tvlUsd','TVL (USD)'],['source','Source'],['fetchedAt','Fetched / age'],['sourceTimestamp','Observed / age']] as const;
const numeric=(v:any)=>v===null||v===undefined?'unknown':Number(v).toLocaleString('en-US',{maximumFractionDigits:3});
const age=(s:any)=>s===null||s===undefined?'unknown':s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m`:s<86400?`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`:`${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h`;
const link=(url:string,label:string)=><a href={url} target="_blank" rel="noopener noreferrer">{label}</a>;
export function StakingScreen(){
 const [data,D]=useState<any>(null),[filters,F]=useState<any>({}),[sort,S]=useState('asset'),[direction,V]=useState('asc'),[error,E]=useState(''),[busy,B]=useState(false),[tick,T]=useState(Date.now()),[refresh,R]=useState(0),[ready,Y]=useState(false),[saveError,SE]=useState('');
 useEffect(()=>{fetch('/api/staking/view').then(r=>r.json()).then(f=>{F(f);S(f.sort??'asset');V(f.direction??'asc');Y(true)}).catch(()=>{SE('Saved view unavailable.');Y(true)})},[]);
 useEffect(()=>{if(!ready)return;const id=setTimeout(()=>{const clean:any={sort,direction};for(const [k,v] of Object.entries(filters))if(v!==''&&v!==undefined)clean[k]=['minTvlUsd','maxLockDays'].includes(k)?Number(v):v;fetch('/api/staking/view',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(clean)}).then(r=>{if(!r.ok)throw Error();SE('')}).catch(()=>SE('View could not be saved.'))},400);return ()=>clearTimeout(id)},[filters,sort,direction,ready]);
 useEffect(()=>{const id=setInterval(()=>T(Date.now()),30000);return ()=>clearInterval(id)},[]);
 useEffect(()=>{if(!ready)return;const controller=new AbortController();B(true);E('');const query=new URLSearchParams({sort,direction});for(const [k,v] of Object.entries(filters))if(v!==''&&v!==false&&v!==undefined)query.set(k,Array.isArray(v)?JSON.stringify(v):String(v));fetch('/api/staking?'+query,{signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error??'Staking data unavailable');D(b);T(Date.now());}).catch(e=>{if(e.name!=='AbortError'){D(null);E(e.message)}}).finally(()=>{if(!controller.signal.aborted)B(false)});return ()=>controller.abort()},[filters,sort,direction,refresh,ready]);
 const filter=(key:string,value:any)=>F({...filters,[key]:value});
 const sortBy=(key:string)=>{if(key===sort)V(direction==='asc'?'desc':'asc');else{S(key);V('asc')}};
 const currentAge=(stamp:string|null)=>stamp?Math.max(0,Math.floor((tick-Date.parse(stamp))/1000)):null;
 function cell(o:any,key:string){
  switch(key){
   case 'asset':return <><b>{o.asset}</b><small>{o.chain}</small></>;
   case 'apy':return <>{numeric(o.apy)}{o.apy!==null&&'%'}<small>base: {numeric(o.baseApy)}{o.baseApy!==null&&'%'}<br/>reward: {numeric(o.rewardApy)}{o.rewardApy!==null&&'%'}</small></>;
   case 'apr':return <>{numeric(o.apr)}{o.apr!==null&&'%'}</>;
   case 'lockDays':return o.lockUp??(o.lockDays===null?'unknown':o.lockDays+' days');
   case 'minimum':return numeric(o.minimum);
   case 'tvlUsd':return numeric(o.tvlUsd);
   case 'risks':return <>{o.risks.length?o.risks.join(', '):'unknown'}{o.risks.length>0&&<small>{link(o.riskSource,'Risk disclosure')}</small>}</>;
   case 'source':return <>{link(o.sourceUrl,o.source)}<small>{link(o.docsUrl,'API docs')}</small></>;
   case 'fetchedAt':{const seconds=currentAge(o.fetchedAt);return <><time>{o.fetchedAt}</time><small>{age(seconds)} old · {seconds===null||seconds>=900?'STALE cached snapshot':'cached snapshot'}</small></>;}
   case 'sourceTimestamp':{const seconds=currentAge(o.sourceTimestamp);return <><time>{o.sourceTimestamp??'unknown'}</time><small>{age(seconds)} old{seconds!==null&&seconds>=129600?' · STALE source observation':''}</small></>;}
   default:return o[key]??'unknown';
  }
 }
 return <section aria-label="Staking information"><article className="staking-notice" role="note"><b>Information only. Not financial advice.</b><p>Rates change. Check the venue before making your own choice. EU/France availability is unknown unless a source states it. APR is not APY; unknown is not zero.</p><p className="muted">Only your enabled sources are used. Source coverage is not a complete market survey. Authenticated exchange listings have not yet been tested with real keys. Nothing can be deposited, staked or ordered here.</p></article>
 <article className="staking-controls"><h2>Choose the view</h2><p>Optional presets. Combine and edit them; none is preferred. Your view is saved in this workspace.</p><div className="preset-grid">{[['staking','Staking and liquid staking only'],['tvl','TVL at least $10M'],['rewards','Exclude promo or reward-only yield'],['exchange','Exchange custody only'],['onchain','On-chain custody only']].map(([id,label])=><label className="check" key={id}><input type="checkbox" checked={(filters.presets??[]).includes(id)} onChange={e=>{const presets=e.target.checked?[...(filters.presets??[]),id]:(filters.presets??[]).filter((p:string)=>p!==id);F({...filters,presets,...(id==='tvl'?{minTvlUsd:e.target.checked?10000000:''}:{})})}}/>{label}</label>)}</div><p className="error">{saveError}</p><div className="staking-filter-grid">
 <label>Asset filter<input value={filters.asset??''} maxLength={32} placeholder="e.g. ETH" onChange={e=>filter('asset',e.target.value)}/></label>
 <label>Type filter<select aria-label="Type filter" value={filters.type??''} onChange={e=>filter('type',e.target.value)}><option value="">All types</option>{['exchange earn','on-chain staking','liquid staking','lending pool','yield pool (classification unknown)'].map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Custody filter<select aria-label="Custody filter" value={filters.custody??''} onChange={e=>filter('custody',e.target.value)}><option value="">All custody</option>{['exchange holds coins','user on-chain','unknown'].map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Max lock-up (days)<input type="number" min="0" max="36500" step="any" value={filters.maxLockDays??''} placeholder="No limit" onChange={e=>filter('maxLockDays',e.target.value)}/></label>
 <label>Min TVL (USD)<input type="number" min="0" max="1000000000000000" step="any" value={filters.minTvlUsd??''} placeholder="No minimum" onChange={e=>filter('minTvlUsd',e.target.value)}/></label>
 <label className="check"><input type="checkbox" checked={!!filters.hidePromo} onChange={e=>filter('hidePromo',e.target.checked)}/>Hide promo or unknown promo status</label>
 <label>Sort column<select aria-label="Sort column" value={sort} onChange={e=>S(e.target.value)}>{columns.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label>Sort direction<select aria-label="Sort direction" value={direction} onChange={e=>V(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label>
 </div><button disabled={busy} onClick={()=>R(refresh+1)}>Check cached data</button><button onClick={()=>{F({});S('asset');V('asc')}}>Reset view</button>
 <p className="muted">Default: asset A–Z, not a quality ranking. Numeric limits exclude unknown values, even with a zero limit. Hiding promos also excludes unknown promo status. The reward preset requires explicit non-promo status, positive base APY and zero reward APY; unknowns are excluded. Staking types require explicit source categories, never protocol-name guesses. Conflicting custody presets produce an empty view. Unknowns sort last in both directions. API refresh is limited to once per 15 minutes.</p></article>
 <p role="status">{busy?'Loading timestamped snapshots…':data?`${data.options.length} shown · ${data.matched} matched of ${data.total} options · ${data.sourceStatus}`:''}</p><p role="alert" className="error">{error}</p>
 {data&&<article className="staking-results"><h2>Options</h2><div className="table-wrap"><table className="staking-table"><caption>Neutral source data. Click a column header to sort; use sort controls on mobile.</caption><thead><tr>{columns.map(([key,label])=><th key={key} scope="col" aria-sort={sort===key?(direction==='asc'?'ascending':'descending'):'none'}><button onClick={()=>sortBy(key)}>{label}{sort===key?(direction==='asc'?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{data.options.map((o:any)=><tr key={o.id}>{columns.map(([key,label])=><td key={key} data-label={label}>{cell(o,key)}</td>)}</tr>)}</tbody></table></div>{!data.options.length&&<>{data.coverage.every((s:any)=>s.status==='disabled')&&<SourceEmpty/>}<p>No options match this view. Source coverage and unknown fields can limit results.</p></>}{data.matched>100&&<p>Showing the first 100 after your sort and filters. Narrow the asset filter to inspect other pools.</p>}<p className="muted">Listed risks come from the linked protocol disclosure, not a risk score or an exhaustive assessment. Lock-up, unbonding, minimum, TVL, APY and promo status are unknown when a feed does not supply them. Net-of-inflation yield is omitted: a verifiable, comparable inflation feed has not been integrated.</p>
 <details className="staking-coverage"><summary>Source coverage and gaps</summary>{data.coverage.map((s:any)=><p key={s.source}><b>{s.source}</b> · {s.status}<small>{s.detail}</small></p>)}</details></article>}
 </section>;
}
