import React,{useEffect,useState} from 'react';
import {SourceEmpty} from './DataSources.js';
import {flowExplanation,washNotice,quoteNotice,trendDefinitions} from '../src/trend-copy.js';
// Copy stays in sync without importing the server connector graph into the browser.
const metricNames={leaders:'Volume leaders',surges:'Volume surges',flow:'Aggressor flow',listings:'New listings',futures:'Futures positioning'};
const num=(v:any,d=2)=>v===null||v===undefined?'unknown':Number(v).toLocaleString('en-US',{maximumFractionDigits:d});
function Spark({history,label,value='value'}:any){const values=(history??[]).map((p:any)=>p[value]).filter((v:any)=>typeof v==='number'&&Number.isFinite(v));if(values.length<2)return <small>History: unknown (at least two observations needed)</small>;const min=Math.min(...values),max=Math.max(...values);return <svg className="trend-spark" viewBox="0 0 220 50" role="img" aria-label={label}><title>{label}</title><path d={values.map((v:number,i:number)=>`${i?'L':'M'}${4+i/(values.length-1)*212},${45-(v-min)/(max-min||1)*40}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function Stamp({source}:any){return <small><a href={source.sourceUrl} target="_blank" rel="noopener noreferrer">{source.source}</a> · fetched <time>{source.fetchedAt??'unknown'}</time> · {source.ageSeconds===null?'unknown':source.ageSeconds+'s'} old · {source.status}</small>}
function exchangeBreakdown(rows:any[]){const groups=new Map<string,any>();for(const row of rows){const old=groups.get(row.exchange);if(old){old.volumeUsd+=row.volumeUsd;old.approximate||=row.approximate;old.markets.push(row)}else groups.set(row.exchange,{...row,markets:[row]})}return [...groups.values()]}
function Bench({row,onBench}:any){return <button onClick={()=>onBench({exchange:row.exchange,symbol:row.symbol})}>Test in bench · past behaviour</button>}
export function TrendsScreen({sourceData,onBench}:any){const enabled=sourceData.sources.filter((s:any)=>s.exchange&&!s.key&&s.enabled),[metric,M]=useState<keyof typeof metricNames>('leaders'),[data,D]=useState<any>(null),[busy,B]=useState(false),[error,E]=useState(''),[n,N]=useState(3),[exchange,X]=useState(enabled[0]?.id??''),[symbol,S]=useState('BTC/USDT'),[window,W]=useState('1h'),[refresh,R]=useState(0),[tick,T]=useState(Date.now()),[leaderLimit,LL]=useState(5);
 useEffect(()=>{if(enabled.length&&!enabled.some((s:any)=>s.id===exchange)){X(enabled[0].id);if(enabled[0].id==='coinbase')S('BTC/USD')}},[sourceData]);
 useEffect(()=>{const id=setInterval(()=>T(Date.now()),30000);return ()=>clearInterval(id)},[]);
 const sourceKey=enabled.map((s:any)=>s.id).join(',');
 useEffect(()=>{if(!sourceKey){D(null);return}let active=true;B(true);D(null);E('');const filters:any={metric,exchanges:sourceKey.split(',')};if(metric==='surges')filters.topN=n;if(['flow','futures'].includes(metric)){filters.exchange=exchange;filters.symbol=symbol;filters.window=window;}fetch('/api/trends',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(filters)}).then(async r=>{const body=await r.json();if(!r.ok)throw Error('Trend snapshot unavailable. Check the selected market and source.');if(active){D(body);T(Date.now())}}).catch(e=>{if(active)E(e.message)}).finally(()=>{if(active)B(false)});return ()=>{active=false}},[metric,n,exchange,symbol,window,refresh,sourceKey]);
 const stamp=(s:any)=><Stamp source={{...s,ageSeconds:s.fetchedAt?Math.max(0,Math.floor((tick-Date.parse(s.fetchedAt))/1000)):null}}/>;
 return <section aria-label="Trends information"><article className="trend-intro"><h2>What is being traded</h2><p>Observed activity, not prediction. Volume is turnover, not a count of people or net capital entering an asset. You choose sources and views.</p><p className="muted">Enabled sources only. Access rights and provider restrictions still apply. Unknown is not zero.</p></article>
 {!enabled.length?<SourceEmpty/>:<><article className="trend-controls"><div className="actions">{Object.entries(metricNames).map(([id,label])=><button key={id} aria-current={metric===id?'page':undefined} onClick={()=>M(id as any)}>{label}</button>)}</div><p>{trendDefinitions[metric]}</p>{metric==='surges'&&<label>Top markets per exchange (N)<select aria-label="Top markets per exchange" value={n} onChange={e=>N(Number(e.target.value))}>{[1,3,5,10].map(v=><option key={v}>{v}</option>)}</select><small>Only the top {n} USD-quoted spot markets per exchange, mechanically selected by reported volume. Daily history is fetched lazily here and cached for one hour. Exchange rate limits apply.</small></label>}
 {['flow','futures'].includes(metric)&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);X(String(f.get('exchange')));S(String(f.get('symbol')));W(String(f.get('window')??'1h'));R(refresh+1)}}><label>Enabled exchange<select name="exchange" defaultValue={exchange} key={exchange}>{enabled.map((s:any)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Spot market<input name="symbol" defaultValue={symbol} key={symbol} pattern="[A-Z0-9.\-]{1,20}/[A-Z0-9.\-]{1,15}" required/></label>{metric==='flow'&&<label>Requested window<select name="window" defaultValue={window}><option>1h</option><option>24h</option></select></label>}<button disabled={busy}>Read selected market</button></form>}
 <button disabled={busy} onClick={()=>R(refresh+1)}>Check cached snapshots</button><small>Volume and futures cache: 5 minutes. Trades: 1 minute. Market lists: 15 minutes. Fetch time and provider observation time are different.</small></article>
 {['leaders','surges','flow'].includes(metric)&&<article role="note" className="trend-warning"><b>Reported-volume limitations</b><p>{washNotice}</p><p>{quoteNotice}</p></article>}
 {metric==='flow'&&<article role="note"><p>{flowExplanation}</p><small>One request, at most 1,000 recent trades. Exchanges may return much less. Partial samples cannot describe the full window.</small></article>}
 <p role="status">{busy?'Reading enabled public sources…':data?'Snapshot captured '+data.asOf:''}</p><p className="error" role="alert">{error}</p>
 {data&&<div className="trend-results">
 {metric==='leaders'&&<article><h2>Combined volume · USD-equivalent</h2><p>All normalized markets from enabled sources are summed by their exchange base-asset code. Codes may collide; these are not verified token identities. Same activity across venues is not unique demand.</p><button onClick={()=>LL(leaderLimit===5?20:5)}>{leaderLimit===5?'Show first 20 assets':'Show first 5 assets'}</button>{data.combined.slice(0,leaderLimit).map((r:any)=><div className="trend-row" key={r.asset}><h3>{r.asset} · ${num(r.volumeUsd)}{r.approximate?' · approximate':''}</h3><div className="trend-breakdown">{exchangeBreakdown(r.breakdown).map((b:any)=><div key={b.exchange+':'+b.symbol}><b>{b.exchange} · {b.markets.length} markets</b><span>${num(b.volumeUsd)}{b.approximate?' (approximate)':''}</span><small>Fetched: {b.fetchedAt} · provider observed: {b.observedAt??'unknown'}</small><details><summary>Market detail and history</summary>{b.markets.map((m:any)=><div key={m.symbol}><small>{m.symbol}: ${num(m.volumeUsd)} · observed {m.observedAt??'unknown'}</small><Spark history={m.history} label={m.symbol+' reported volume snapshots'}/><Bench row={m} onBench={onBench}/></div>)}</details><Bench row={b} onBench={onBench}/></div>)}</div></div>)}{!data.combined.length&&<p>Volume: unknown.</p>}<p>Showing the first {leaderLimit} base-asset codes by the displayed numeric value. Per-exchange summaries below include exclusion counts.</p></article>}
 {data.sources.map((s:any)=><article key={s.exchange}><h2>{s.exchange} · {metricNames[metric]}</h2>{stamp(s)}
 {['leaders','surges'].includes(metric)&&<p>{s.marketCount??'unknown'} spot markets · excluded quote: {s.excludedQuote??'unknown'} · excluded missing turnover: {s.excludedData??'unknown'} · normalized: {s.rows?.length??0}{metric==='surges'?' (capped universe)':''}</p>}
 {metric==='leaders'&&<div className="table-wrap"><table className="trend-volume-table"><thead><tr><th>Market</th><th>24h USD-equivalent</th><th>Observed at</th><th>Past behaviour</th></tr></thead><tbody>{[...(s.rows??[])].sort((a:any,b:any)=>b.volumeUsd-a.volumeUsd).slice(0,10).map((r:any)=><tr key={r.symbol}><td data-label="Market">{r.symbol}</td><td data-label="24h USD-equivalent">${num(r.volumeUsd)}{r.approximate?' · approximate':''}</td><td data-label="Observed at">{r.observedAt??'unknown'}</td><td><Bench row={r} onBench={onBench}/></td></tr>)}</tbody></table><small>First 10 markets shown per exchange; combined totals use all normalized markets. Volume snapshot mini-charts are shown in the combined breakdown when at least two observations exist.</small></div>}
 {metric==='surges'&&(s.rows??[]).map((r:any)=><div className="trend-row" key={r.symbol}><h3>{r.symbol} · ratio {num(r.ratio)}{r.ratio!==null?'×':''}</h3><p>24h: ${num(r.volumeUsd)} · prior daily average: {r.averageDailyUsd===null?'unknown':'$'+num(r.averageDailyUsd)} · {r.days}/30 complete daily candles · approximate turnover</p><small>Daily history fetched: {r.historyFetchedAt??'unknown'} · provider ticker observed: {r.observedAt??'unknown'}</small><Spark history={r.history} label={r.symbol+' prior daily turnover history'}/><Bench row={r} onBench={onBench}/></div>)}
 {metric==='flow'&&s.sample&&<><h3>{s.symbol} · {s.window} requested</h3><p>Full-window buyer-initiated: {num(s.windowAcquisitionUsd)} USD-equivalent · seller-initiated: {num(s.windowDisposalUsd)} USD-equivalent</p><p><b>{s.complete?'Window start reached':'Partial history; full-window totals unknown'}</b></p><h3>Observed sample only</h3><p>Buyer-initiated: ${num(s.sample.acquisitionUsd)} · seller-initiated: ${num(s.sample.disposalUsd)} · share of known turnover: {s.sample.acquisitionShare===null?'unknown':num(s.sample.acquisitionShare*100)+'%'}</p><p>{s.sample.observedCount} classified · {s.sample.unknownCount} unknown/excluded · sample {s.sample.oldest??'unknown'} to {s.sample.newest??'unknown'}</p><Spark history={s.history} value="acquisitionUsd" label="Buyer-initiated sample turnover by time bucket"/><Spark history={s.history} value="disposalUsd" label="Seller-initiated sample turnover by time bucket"/><small>{s.semantics}</small><Bench row={s} onBench={onBench}/></>}
 {metric==='listings'&&<><p>{s.baseline?'Baseline taken. First run cannot identify new listings.':`Changes since ${s.previousSnapshotAt??'unknown'}. Snapshots can miss markets appearing and disappearing between checks.`}</p><p>{s.marketCount??'unknown'} active spot markets · {(s.added??[]).length} appeared in this comparison.</p>{(s.added??[]).map((r:any)=><div className="trend-row" key={r.symbol}><b>{r.symbol}</b><small>First seen here: {r.firstSeen}</small><Bench row={{...r,exchange:s.exchange}} onBench={onBench}/></div>)}{s.history?.length>0&&<details><summary>Previous first-seen records (up to 50)</summary>{s.history.map((r:any)=><p key={r.symbol}>{r.symbol} · {r.firstSeen}</p>)}</details>}</>}
 {metric==='futures'&&<><h3>{s.contract??'Contract unknown'}</h3><div className="metrics">{[['Funding rate',s.fundingRate===null||s.fundingRate===undefined?'unknown':num(s.fundingRate*100,6)+'%'],['Open interest amount',num(s.openInterestAmount)],['Open interest USD value',num(s.openInterestValue)],['Perpetual / spot basis',s.basisPct===null||s.basisPct===undefined?'unknown':num(s.basisPct,5)+'%']].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><p>Funding observed: {s.fundingTimestamp??'unknown'} · next funding: {s.nextFundingAt??'unknown'}</p><p>Interest observed: {s.interestTimestamp??'unknown'} · price observed: {s.priceObservedAt??'unknown'}</p><small>Amount uses the provider's reported units; contract size is not converted. USD value only if supplied by ccxt. The next funding interval can be unknown.</small><Spark history={s.history} label="Funding snapshots in this installation"/><Bench row={{exchange:s.exchange,symbol:s.symbol??symbol}} onBench={onBench}/></>}
 {s.status.startsWith('unknown')&&<p>Metric value: unknown.</p>}
 </article>)}
 </div>}</>}
 </section>;
}
